// Mocks generated by Mockito 5.4.6 from annotations
// in squad_sync/test/discovery_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:typed_data' as _i13;
import 'dart:ui' as _i11;

import 'package:cloud_firestore/cloud_firestore.dart' as _i5;
import 'package:firebase_core/firebase_core.dart' as _i4;
import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:sqflite/sqflite.dart' as _i3;
import 'package:squad_sync/chat/sqlite_helper.dart' as _i12;
import 'package:squad_sync/managers/notification_manager.dart' as _i9;
import 'package:squad_sync/services/firestore_service_refactored.dart' as _i2;
import 'package:squad_sync/services/grok_service.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOptimizedGroupQueryBuilder_0 extends _i1.SmartFake
    implements _i2.OptimizedGroupQueryBuilder {
  _FakeOptimizedGroupQueryBuilder_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabase_1 extends _i1.SmartFake implements _i3.Database {
  _FakeDatabase_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseApp_2 extends _i1.SmartFake implements _i4.FirebaseApp {
  _FakeFirebaseApp_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSettings_3 extends _i1.SmartFake implements _i5.Settings {
  _FakeSettings_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCollectionReference_4<T extends Object?> extends _i1.SmartFake
    implements _i5.CollectionReference<T> {
  _FakeCollectionReference_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWriteBatch_5 extends _i1.SmartFake implements _i5.WriteBatch {
  _FakeWriteBatch_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLoadBundleTask_6 extends _i1.SmartFake
    implements _i5.LoadBundleTask {
  _FakeLoadBundleTask_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuerySnapshot_7<T1 extends Object?> extends _i1.SmartFake
    implements _i5.QuerySnapshot<T1> {
  _FakeQuerySnapshot_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuery_8<T extends Object?> extends _i1.SmartFake
    implements _i5.Query<T> {
  _FakeQuery_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDocumentReference_9<T extends Object?> extends _i1.SmartFake
    implements _i5.DocumentReference<T> {
  _FakeDocumentReference_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_10<T1> extends _i1.SmartFake implements _i6.Future<T1> {
  _FakeFuture_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i2.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.OptimizedGroupQueryBuilder get queryBuilder => (super.noSuchMethod(
        Invocation.getter(#queryBuilder),
        returnValue: _FakeOptimizedGroupQueryBuilder_0(
          this,
          Invocation.getter(#queryBuilder),
        ),
      ) as _i2.OptimizedGroupQueryBuilder);

  @override
  set queryBuilder(_i2.OptimizedGroupQueryBuilder? _queryBuilder) =>
      super.noSuchMethod(
        Invocation.setter(
          #queryBuilder,
          _queryBuilder,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<Map<String, dynamic>?> loadDocument(
    String? collection,
    String? document,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadDocument,
          [
            collection,
            document,
          ],
        ),
        returnValue: _i6.Future<Map<String, dynamic>?>.value(),
      ) as _i6.Future<Map<String, dynamic>?>);

  @override
  _i6.Future<bool> saveDocument(
    String? collection,
    String? document,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveDocument,
          [
            collection,
            document,
            data,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> batchWrite(List<_i5.WriteBatch>? operations) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchWrite,
          [operations],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> cleanupExpiredCache() => (super.noSuchMethod(
        Invocation.method(
          #cleanupExpiredCache,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Stream<Map<String, dynamic>?> getVoiceRoomStream(String? roomId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVoiceRoomStream,
          [roomId],
        ),
        returnValue: _i6.Stream<Map<String, dynamic>?>.empty(),
      ) as _i6.Stream<Map<String, dynamic>?>);

  @override
  _i6.Future<void> updateVoiceRoom(
    String? roomId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateVoiceRoom,
          [
            roomId,
            data,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateVoiceParticipant(
    String? roomId,
    String? uid,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateVoiceParticipant,
          [
            roomId,
            uid,
            data,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [GrokService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGrokService extends _i1.Mock implements _i7.GrokService {
  MockGrokService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool isMessageForGrok(String? message) => (super.noSuchMethod(
        Invocation.method(
          #isMessageForGrok,
          [message],
        ),
        returnValue: false,
      ) as bool);

  @override
  String cleanGrokMessage(String? message) => (super.noSuchMethod(
        Invocation.method(
          #cleanGrokMessage,
          [message],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #cleanGrokMessage,
            [message],
          ),
        ),
      ) as String);

  @override
  _i6.Future<String> getGrokResponse(
    String? userMessage, {
    String? context,
    List<String>? recentMessages,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGrokResponse,
          [userMessage],
          {
            #context: context,
            #recentMessages: recentMessages,
          },
        ),
        returnValue: _i6.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #getGrokResponse,
            [userMessage],
            {
              #context: context,
              #recentMessages: recentMessages,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<String> suggestSquadsForPinnedGames(
          List<Map<String, dynamic>>? pinnedGames) =>
      (super.noSuchMethod(
        Invocation.method(
          #suggestSquadsForPinnedGames,
          [pinnedGames],
        ),
        returnValue: _i6.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #suggestSquadsForPinnedGames,
            [pinnedGames],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<List<double>> getGroupEmbeddings(
          Map<String, dynamic>? groupData) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroupEmbeddings,
          [groupData],
        ),
        returnValue: _i6.Future<List<double>>.value(<double>[]),
      ) as _i6.Future<List<double>>);

  @override
  _i6.Future<Map<String, double>> scoreRelevance(
    String? searchTerm,
    List<String>? candidates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #scoreRelevance,
          [
            searchTerm,
            candidates,
          ],
        ),
        returnValue: _i6.Future<Map<String, double>>.value(<String, double>{}),
      ) as _i6.Future<Map<String, double>>);
}

/// A class which mocks [NotificationManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationManager extends _i1.Mock
    implements _i9.NotificationManager {
  MockNotificationManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get notificationsEnabled => (super.noSuchMethod(
        Invocation.getter(#notificationsEnabled),
        returnValue: false,
      ) as bool);

  @override
  Map<String, bool> get notificationTypes => (super.noSuchMethod(
        Invocation.getter(#notificationTypes),
        returnValue: <String, bool>{},
      ) as Map<String, bool>);

  @override
  set notificationsEnabled(bool? _notificationsEnabled) => super.noSuchMethod(
        Invocation.setter(
          #notificationsEnabled,
          _notificationsEnabled,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set notificationTypes(Map<String, bool>? _notificationTypes) =>
      super.noSuchMethod(
        Invocation.setter(
          #notificationTypes,
          _notificationTypes,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<void> updateFCMToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #updateFCMToken,
          [token],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> removeFCMToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #removeFCMToken,
          [token],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateNotificationSettings(Map<String, bool>? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNotificationSettings,
          [settings],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<Map<String, bool>> getNotificationSettings() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotificationSettings,
          [],
        ),
        returnValue: _i6.Future<Map<String, bool>>.value(<String, bool>{}),
      ) as _i6.Future<Map<String, bool>>);

  @override
  void setNotificationsEnabled(bool? enabled) => super.noSuchMethod(
        Invocation.method(
          #setNotificationsEnabled,
          [enabled],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setNotificationType(
    String? type,
    bool? enabled,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setNotificationType,
          [
            type,
            enabled,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isNotificationEnabled(String? type) => (super.noSuchMethod(
        Invocation.method(
          #isNotificationEnabled,
          [type],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<void> showNotification({
    required String? title,
    required String? body,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showNotification,
          [],
          {
            #title: title,
            #body: body,
            #payload: payload,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> scheduleNotification({
    required String? title,
    required String? body,
    required DateTime? scheduledTime,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleNotification,
          [],
          {
            #title: title,
            #body: body,
            #scheduledTime: scheduledTime,
            #payload: payload,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> cancelNotification(int? id) => (super.noSuchMethod(
        Invocation.method(
          #cancelNotification,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> cancelAllNotifications() => (super.noSuchMethod(
        Invocation.method(
          #cancelAllNotifications,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> showSmartNotification({
    required String? title,
    required String? body,
    required String? channelId,
    String? payload,
    List<_i10.AndroidNotificationAction>? actions,
    bool? ongoing = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showSmartNotification,
          [],
          {
            #title: title,
            #body: body,
            #channelId: channelId,
            #payload: payload,
            #actions: actions,
            #ongoing: ongoing,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> showTimerWarning(
    String? player,
    int? minutesLeft,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #showTimerWarning,
          [
            player,
            minutesLeft,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> showBanWarning(
    String? player,
    int? banCount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #showBanWarning,
          [
            player,
            banCount,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> showAchievementNotification(
    String? player,
    String? achievement,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #showAchievementNotification,
          [
            player,
            achievement,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> showSquadSpotNotification(
    String? game,
    String? spotClaimedBy,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #showSquadSpotNotification,
          [
            game,
            spotClaimedBy,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> showChatMentionNotification(
    String? sender,
    String? message,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #showChatMentionNotification,
          [
            sender,
            message,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> showPersistentLobbyNotification({
    required String? lobbyId,
    required String? gameName,
    required String? hostName,
    required int? currentPlayers,
    required int? maxPlayers,
    required List<String>? playerNames,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showPersistentLobbyNotification,
          [],
          {
            #lobbyId: lobbyId,
            #gameName: gameName,
            #hostName: hostName,
            #currentPlayers: currentPlayers,
            #maxPlayers: maxPlayers,
            #playerNames: playerNames,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> dismissPersistentLobbyNotification(String? lobbyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #dismissPersistentLobbyNotification,
          [lobbyId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> checkAndShowFriendLobbyNotifications() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkAndShowFriendLobbyNotifications,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Stream<List<_i5.QueryDocumentSnapshot<Map<String, dynamic>>>>
      getFilteredNotificationsStream({Set<String>? mutedGames}) =>
          (super.noSuchMethod(
            Invocation.method(
              #getFilteredNotificationsStream,
              [],
              {#mutedGames: mutedGames},
            ),
            returnValue: _i6.Stream<
                List<_i5.QueryDocumentSnapshot<Map<String, dynamic>>>>.empty(),
          ) as _i6
              .Stream<List<_i5.QueryDocumentSnapshot<Map<String, dynamic>>>>);

  @override
  _i6.Stream<int> getUnreadNotificationCount() => (super.noSuchMethod(
        Invocation.method(
          #getUnreadNotificationCount,
          [],
        ),
        returnValue: _i6.Stream<int>.empty(),
      ) as _i6.Stream<int>);

  @override
  _i6.Future<void> createNotification({
    required String? type,
    required String? title,
    required String? body,
    String? game,
    Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNotification,
          [],
          {
            #type: type,
            #title: title,
            #body: body,
            #game: game,
            #data: data,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> markAsRead(String? notificationId) => (super.noSuchMethod(
        Invocation.method(
          #markAsRead,
          [notificationId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> archiveNotification(String? notificationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #archiveNotification,
          [notificationId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SQLiteHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockSQLiteHelper extends _i1.Mock implements _i12.SQLiteHelper {
  MockSQLiteHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i6.Future<_i3.Database>.value(_FakeDatabase_1(
          this,
          Invocation.getter(#database),
        )),
      ) as _i6.Future<_i3.Database>);

  @override
  _i6.Future<void> insertMessage(
    Map<String, dynamic>? message, {
    String? chatGroupId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertMessage,
          [message],
          {#chatGroupId: chatGroupId},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateMessage(
    String? msgId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMessage,
          [
            msgId,
            updates,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clearMessages({String? chatGroupId}) => (super.noSuchMethod(
        Invocation.method(
          #clearMessages,
          [],
          {#chatGroupId: chatGroupId},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getMessages(
    int? offset,
    int? limit, {
    String? chatGroupId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessages,
          [
            offset,
            limit,
          ],
          {#chatGroupId: chatGroupId},
        ),
        returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getCachedGroups(
    String? gameName,
    String? searchTerm,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedGroups,
          [
            gameName,
            searchTerm,
          ],
        ),
        returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<void> cacheGroups(
    List<Map<String, dynamic>>? groups,
    String? gameName,
    String? searchTerm,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheGroups,
          [
            groups,
            gameName,
            searchTerm,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getCachedGames(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedGames,
          [query],
        ),
        returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<void> cacheGames(
    List<Map<String, dynamic>>? games,
    String? query,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheGames,
          [
            games,
            query,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>?> getCacheMetadata(String? cacheKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCacheMetadata,
          [cacheKey],
        ),
        returnValue: _i6.Future<Map<String, dynamic>?>.value(),
      ) as _i6.Future<Map<String, dynamic>?>);

  @override
  _i6.Future<void> insertCacheMetadata(
    String? cacheKey,
    int? timestamp,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertCacheMetadata,
          [
            cacheKey,
            timestamp,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> cleanupExpiredCache(Duration? ttl) => (super.noSuchMethod(
        Invocation.method(
          #cleanupExpiredCache,
          [ttl],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> cacheVoiceRoom(
    String? roomId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheVoiceRoom,
          [
            roomId,
            data,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>?> getCachedVoiceRoom(String? roomId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedVoiceRoom,
          [roomId],
        ),
        returnValue: _i6.Future<Map<String, dynamic>?>.value(),
      ) as _i6.Future<Map<String, dynamic>?>);
}

/// A class which mocks [FirebaseFirestore].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseFirestore extends _i1.Mock implements _i5.FirebaseFirestore {
  MockFirebaseFirestore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.FirebaseApp get app => (super.noSuchMethod(
        Invocation.getter(#app),
        returnValue: _FakeFirebaseApp_2(
          this,
          Invocation.getter(#app),
        ),
      ) as _i4.FirebaseApp);

  @override
  String get databaseId => (super.noSuchMethod(
        Invocation.getter(#databaseId),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#databaseId),
        ),
      ) as String);

  @override
  _i5.Settings get settings => (super.noSuchMethod(
        Invocation.getter(#settings),
        returnValue: _FakeSettings_3(
          this,
          Invocation.getter(#settings),
        ),
      ) as _i5.Settings);

  @override
  set app(_i4.FirebaseApp? _app) => super.noSuchMethod(
        Invocation.setter(
          #app,
          _app,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set databaseId(String? _databaseId) => super.noSuchMethod(
        Invocation.setter(
          #databaseId,
          _databaseId,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set settings(_i5.Settings? settings) => super.noSuchMethod(
        Invocation.setter(
          #settings,
          settings,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<dynamic, dynamic> get pluginConstants => (super.noSuchMethod(
        Invocation.getter(#pluginConstants),
        returnValue: <dynamic, dynamic>{},
      ) as Map<dynamic, dynamic>);

  @override
  _i5.CollectionReference<Map<String, dynamic>> collection(
          String? collectionPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #collection,
          [collectionPath],
        ),
        returnValue: _FakeCollectionReference_4<Map<String, dynamic>>(
          this,
          Invocation.method(
            #collection,
            [collectionPath],
          ),
        ),
      ) as _i5.CollectionReference<Map<String, dynamic>>);

  @override
  _i5.WriteBatch batch() => (super.noSuchMethod(
        Invocation.method(
          #batch,
          [],
        ),
        returnValue: _FakeWriteBatch_5(
          this,
          Invocation.method(
            #batch,
            [],
          ),
        ),
      ) as _i5.WriteBatch);

  @override
  _i6.Future<void> clearPersistence() => (super.noSuchMethod(
        Invocation.method(
          #clearPersistence,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i5.LoadBundleTask loadBundle(_i13.Uint8List? bundle) => (super.noSuchMethod(
        Invocation.method(
          #loadBundle,
          [bundle],
        ),
        returnValue: _FakeLoadBundleTask_6(
          this,
          Invocation.method(
            #loadBundle,
            [bundle],
          ),
        ),
      ) as _i5.LoadBundleTask);

  @override
  void useFirestoreEmulator(
    String? host,
    int? port, {
    bool? sslEnabled = false,
    bool? automaticHostMapping = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #useFirestoreEmulator,
          [
            host,
            port,
          ],
          {
            #sslEnabled: sslEnabled,
            #automaticHostMapping: automaticHostMapping,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<_i5.QuerySnapshot<T>> namedQueryWithConverterGet<T>(
    String? name, {
    _i5.GetOptions? options = const _i5.GetOptions(),
    required _i5.FromFirestore<T>? fromFirestore,
    required _i5.ToFirestore<T>? toFirestore,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #namedQueryWithConverterGet,
          [name],
          {
            #options: options,
            #fromFirestore: fromFirestore,
            #toFirestore: toFirestore,
          },
        ),
        returnValue:
            _i6.Future<_i5.QuerySnapshot<T>>.value(_FakeQuerySnapshot_7<T>(
          this,
          Invocation.method(
            #namedQueryWithConverterGet,
            [name],
            {
              #options: options,
              #fromFirestore: fromFirestore,
              #toFirestore: toFirestore,
            },
          ),
        )),
      ) as _i6.Future<_i5.QuerySnapshot<T>>);

  @override
  _i6.Future<_i5.QuerySnapshot<Map<String, dynamic>>> namedQueryGet(
    String? name, {
    _i5.GetOptions? options = const _i5.GetOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #namedQueryGet,
          [name],
          {#options: options},
        ),
        returnValue: _i6.Future<_i5.QuerySnapshot<Map<String, dynamic>>>.value(
            _FakeQuerySnapshot_7<Map<String, dynamic>>(
          this,
          Invocation.method(
            #namedQueryGet,
            [name],
            {#options: options},
          ),
        )),
      ) as _i6.Future<_i5.QuerySnapshot<Map<String, dynamic>>>);

  @override
  _i5.Query<Map<String, dynamic>> collectionGroup(String? collectionPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #collectionGroup,
          [collectionPath],
        ),
        returnValue: _FakeQuery_8<Map<String, dynamic>>(
          this,
          Invocation.method(
            #collectionGroup,
            [collectionPath],
          ),
        ),
      ) as _i5.Query<Map<String, dynamic>>);

  @override
  _i6.Future<void> disableNetwork() => (super.noSuchMethod(
        Invocation.method(
          #disableNetwork,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i5.DocumentReference<Map<String, dynamic>> doc(String? documentPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #doc,
          [documentPath],
        ),
        returnValue: _FakeDocumentReference_9<Map<String, dynamic>>(
          this,
          Invocation.method(
            #doc,
            [documentPath],
          ),
        ),
      ) as _i5.DocumentReference<Map<String, dynamic>>);

  @override
  _i6.Future<void> enableNetwork() => (super.noSuchMethod(
        Invocation.method(
          #enableNetwork,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Stream<void> snapshotsInSync() => (super.noSuchMethod(
        Invocation.method(
          #snapshotsInSync,
          [],
        ),
        returnValue: _i6.Stream<void>.empty(),
      ) as _i6.Stream<void>);

  @override
  _i6.Future<T> runTransaction<T>(
    _i5.TransactionHandler<T>? transactionHandler, {
    Duration? timeout = const Duration(seconds: 30),
    int? maxAttempts = 5,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #runTransaction,
          [transactionHandler],
          {
            #timeout: timeout,
            #maxAttempts: maxAttempts,
          },
        ),
        returnValue: _i8.ifNotNull(
              _i8.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #runTransaction,
                  [transactionHandler],
                  {
                    #timeout: timeout,
                    #maxAttempts: maxAttempts,
                  },
                ),
              ),
              (T v) => _i6.Future<T>.value(v),
            ) ??
            _FakeFuture_10<T>(
              this,
              Invocation.method(
                #runTransaction,
                [transactionHandler],
                {
                  #timeout: timeout,
                  #maxAttempts: maxAttempts,
                },
              ),
            ),
      ) as _i6.Future<T>);

  @override
  _i6.Future<void> terminate() => (super.noSuchMethod(
        Invocation.method(
          #terminate,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> waitForPendingWrites() => (super.noSuchMethod(
        Invocation.method(
          #waitForPendingWrites,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setIndexConfigurationFromJSON(String? json) =>
      (super.noSuchMethod(
        Invocation.method(
          #setIndexConfigurationFromJSON,
          [json],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
