// Mocks generated by Mockito 5.4.6 from annotations
// in squad_sync/test/game_state_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:squad_sync/domain/entities/game.dart' as _i4;
import 'package:squad_sync/domain/repositories/game_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GameRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameRepository extends _i1.Mock implements _i2.GameRepository {
  MockGameRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Game>> fetchGames(
    String? query, {
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchGames,
          [query],
          {#limit: limit},
        ),
        returnValue: _i3.Future<List<_i4.Game>>.value(<_i4.Game>[]),
      ) as _i3.Future<List<_i4.Game>>);

  @override
  _i3.Future<_i4.Game?> getGameDetails(int? igdbId) => (super.noSuchMethod(
        Invocation.method(
          #getGameDetails,
          [igdbId],
        ),
        returnValue: _i3.Future<_i4.Game?>.value(),
      ) as _i3.Future<_i4.Game?>);

  @override
  _i3.Future<List<_i4.Game>> getPopularGames() => (super.noSuchMethod(
        Invocation.method(
          #getPopularGames,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Game>>.value(<_i4.Game>[]),
      ) as _i3.Future<List<_i4.Game>>);

  @override
  _i3.Future<void> cacheGamesLocally(
    String? query,
    List<_i4.Game>? games,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheGamesLocally,
          [
            query,
            games,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Game>> getCachedGames(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedGames,
          [query],
        ),
        returnValue: _i3.Future<List<_i4.Game>>.value(<_i4.Game>[]),
      ) as _i3.Future<List<_i4.Game>>);

  @override
  _i3.Future<List<_i4.Game>> getOfflineGames(
    String? query, {
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOfflineGames,
          [query],
          {#limit: limit},
        ),
        returnValue: _i3.Future<List<_i4.Game>>.value(<_i4.Game>[]),
      ) as _i3.Future<List<_i4.Game>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getAvailableGames() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableGames,
          [],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, List<Map<String, dynamic>>>> getGameLobbies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getGameLobbies,
          [],
        ),
        returnValue: _i3.Future<Map<String, List<Map<String, dynamic>>>>.value(
            <String, List<Map<String, dynamic>>>{}),
      ) as _i3.Future<Map<String, List<Map<String, dynamic>>>>);
}
