// Mocks generated by Mockito 5.4.6 from annotations
// in squad_sync/test/test_utils.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i29;
import 'dart:io' as _i38;
import 'dart:ui' as _i36;

import 'package:cloud_firestore/cloud_firestore.dart' as _i37;
import 'package:flutter/material.dart' as _i28;
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i24;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i30;
import 'package:sqflite/sqflite.dart' as _i26;
import 'package:squad_sync/chat/chat_service.dart' as _i21;
import 'package:squad_sync/chat/message.dart' as _i32;
import 'package:squad_sync/chat/models/message_data.dart' as _i39;
import 'package:squad_sync/chat/sqlite_helper.dart' as _i35;
import 'package:squad_sync/managers/achievement_manager.dart' as _i6;
import 'package:squad_sync/managers/achievement_service.dart' as _i18;
import 'package:squad_sync/managers/availability_manager.dart' as _i8;
import 'package:squad_sync/managers/game_manager.dart' as _i2;
import 'package:squad_sync/managers/lobby_service.dart' as _i16;
import 'package:squad_sync/managers/notification_coordinator.dart' as _i15;
import 'package:squad_sync/managers/notification_manager.dart' as _i7;
import 'package:squad_sync/managers/peacock_manager.dart' as _i4;
import 'package:squad_sync/managers/peacock_service.dart' as _i17;
import 'package:squad_sync/managers/spot_management_service.dart' as _i20;
import 'package:squad_sync/managers/squad_data_manager.dart' as _i9;
import 'package:squad_sync/managers/squad_manager.dart' as _i3;
import 'package:squad_sync/managers/squad_membership_service.dart' as _i19;
import 'package:squad_sync/managers/squad_persistence_manager.dart' as _i11;
import 'package:squad_sync/managers/squad_persistence_service.dart' as _i14;
import 'package:squad_sync/managers/squad_ui_manager.dart' as _i10;
import 'package:squad_sync/managers/state_initializer.dart' as _i12;
import 'package:squad_sync/managers/timer_state.dart' as _i13;
import 'package:squad_sync/managers/user_manager.dart' as _i5;
import 'package:squad_sync/providers/chat_state_notifier.dart' as _i25;
import 'package:squad_sync/services/ai_service.dart' as _i34;
import 'package:squad_sync/services/message_service.dart' as _i27;
import 'package:squad_sync/services/reaction_service.dart' as _i33;
import 'package:squad_sync/services/services.dart' as _i22;
import 'package:squad_sync/squad_state.dart' as _i23;
import 'package:state_notifier/state_notifier.dart' as _i31;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGameManager_0 extends _i1.SmartFake implements _i2.GameManager {
  _FakeGameManager_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSquadManager_1 extends _i1.SmartFake implements _i3.SquadManager {
  _FakeSquadManager_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePeacockManager_2 extends _i1.SmartFake
    implements _i4.PeacockManager {
  _FakePeacockManager_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserManager_3 extends _i1.SmartFake implements _i5.UserManager {
  _FakeUserManager_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAchievementManager_4 extends _i1.SmartFake
    implements _i6.AchievementManager {
  _FakeAchievementManager_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNotificationManager_5 extends _i1.SmartFake
    implements _i7.NotificationManager {
  _FakeNotificationManager_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAvailabilityManager_6 extends _i1.SmartFake
    implements _i8.AvailabilityManager {
  _FakeAvailabilityManager_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSquadDataManager_7 extends _i1.SmartFake
    implements _i9.SquadDataManager {
  _FakeSquadDataManager_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSquadUIManager_8 extends _i1.SmartFake
    implements _i10.SquadUIManager {
  _FakeSquadUIManager_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSquadPersistenceManager_9 extends _i1.SmartFake
    implements _i11.SquadPersistenceManager {
  _FakeSquadPersistenceManager_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStateInitializer_10 extends _i1.SmartFake
    implements _i12.StateInitializer {
  _FakeStateInitializer_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTimerState_11 extends _i1.SmartFake implements _i13.TimerState {
  _FakeTimerState_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSquadPersistenceService_12 extends _i1.SmartFake
    implements _i14.SquadPersistenceService {
  _FakeSquadPersistenceService_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNotificationCoordinator_13 extends _i1.SmartFake
    implements _i15.NotificationCoordinator {
  _FakeNotificationCoordinator_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLobbyService_14 extends _i1.SmartFake implements _i16.LobbyService {
  _FakeLobbyService_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePeacockService_15 extends _i1.SmartFake
    implements _i17.PeacockService {
  _FakePeacockService_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAchievementService_16 extends _i1.SmartFake
    implements _i18.AchievementService {
  _FakeAchievementService_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSquadMembershipService_17 extends _i1.SmartFake
    implements _i19.SquadMembershipService {
  _FakeSquadMembershipService_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSpotManagementService_18 extends _i1.SmartFake
    implements _i20.SpotManagementService {
  _FakeSpotManagementService_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChatService_19 extends _i1.SmartFake implements _i21.ChatService {
  _FakeChatService_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthService_20 extends _i1.SmartFake implements _i22.AuthService {
  _FakeAuthService_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAudioService_21 extends _i1.SmartFake implements _i22.AudioService {
  _FakeAudioService_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCacheService_22 extends _i1.SmartFake implements _i22.CacheService {
  _FakeCacheService_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSquadStateData_23 extends _i1.SmartFake
    implements _i23.SquadStateData {
  _FakeSquadStateData_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRef_24<State extends Object?> extends _i1.SmartFake
    implements _i24.Ref<State> {
  _FakeRef_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChatStateData_25 extends _i1.SmartFake
    implements _i25.ChatStateData {
  _FakeChatStateData_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabase_26 extends _i1.SmartFake implements _i26.Database {
  _FakeDatabase_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProviderContainer_27 extends _i1.SmartFake
    implements _i24.ProviderContainer {
  _FakeProviderContainer_27(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKeepAliveLink_28 extends _i1.SmartFake
    implements _i24.KeepAliveLink {
  _FakeKeepAliveLink_28(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProviderSubscription_29<State1> extends _i1.SmartFake
    implements _i24.ProviderSubscription<State1> {
  _FakeProviderSubscription_29(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMessageSendResult_30 extends _i1.SmartFake
    implements _i27.MessageSendResult {
  _FakeMessageSendResult_30(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SquadStateNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockSquadStateNotifier extends _i1.Mock
    implements _i23.SquadStateNotifier {
  @override
  _i2.GameManager get gameManager => (super.noSuchMethod(
        Invocation.getter(#gameManager),
        returnValue: _FakeGameManager_0(
          this,
          Invocation.getter(#gameManager),
        ),
        returnValueForMissingStub: _FakeGameManager_0(
          this,
          Invocation.getter(#gameManager),
        ),
      ) as _i2.GameManager);

  @override
  _i3.SquadManager get squadManager => (super.noSuchMethod(
        Invocation.getter(#squadManager),
        returnValue: _FakeSquadManager_1(
          this,
          Invocation.getter(#squadManager),
        ),
        returnValueForMissingStub: _FakeSquadManager_1(
          this,
          Invocation.getter(#squadManager),
        ),
      ) as _i3.SquadManager);

  @override
  _i4.PeacockManager get peacockManager => (super.noSuchMethod(
        Invocation.getter(#peacockManager),
        returnValue: _FakePeacockManager_2(
          this,
          Invocation.getter(#peacockManager),
        ),
        returnValueForMissingStub: _FakePeacockManager_2(
          this,
          Invocation.getter(#peacockManager),
        ),
      ) as _i4.PeacockManager);

  @override
  _i5.UserManager get userManager => (super.noSuchMethod(
        Invocation.getter(#userManager),
        returnValue: _FakeUserManager_3(
          this,
          Invocation.getter(#userManager),
        ),
        returnValueForMissingStub: _FakeUserManager_3(
          this,
          Invocation.getter(#userManager),
        ),
      ) as _i5.UserManager);

  @override
  _i6.AchievementManager get achievementManager => (super.noSuchMethod(
        Invocation.getter(#achievementManager),
        returnValue: _FakeAchievementManager_4(
          this,
          Invocation.getter(#achievementManager),
        ),
        returnValueForMissingStub: _FakeAchievementManager_4(
          this,
          Invocation.getter(#achievementManager),
        ),
      ) as _i6.AchievementManager);

  @override
  _i7.NotificationManager get notificationManager => (super.noSuchMethod(
        Invocation.getter(#notificationManager),
        returnValue: _FakeNotificationManager_5(
          this,
          Invocation.getter(#notificationManager),
        ),
        returnValueForMissingStub: _FakeNotificationManager_5(
          this,
          Invocation.getter(#notificationManager),
        ),
      ) as _i7.NotificationManager);

  @override
  _i8.AvailabilityManager get availabilityManager => (super.noSuchMethod(
        Invocation.getter(#availabilityManager),
        returnValue: _FakeAvailabilityManager_6(
          this,
          Invocation.getter(#availabilityManager),
        ),
        returnValueForMissingStub: _FakeAvailabilityManager_6(
          this,
          Invocation.getter(#availabilityManager),
        ),
      ) as _i8.AvailabilityManager);

  @override
  _i9.SquadDataManager get dataManager => (super.noSuchMethod(
        Invocation.getter(#dataManager),
        returnValue: _FakeSquadDataManager_7(
          this,
          Invocation.getter(#dataManager),
        ),
        returnValueForMissingStub: _FakeSquadDataManager_7(
          this,
          Invocation.getter(#dataManager),
        ),
      ) as _i9.SquadDataManager);

  @override
  _i10.SquadUIManager get uiManager => (super.noSuchMethod(
        Invocation.getter(#uiManager),
        returnValue: _FakeSquadUIManager_8(
          this,
          Invocation.getter(#uiManager),
        ),
        returnValueForMissingStub: _FakeSquadUIManager_8(
          this,
          Invocation.getter(#uiManager),
        ),
      ) as _i10.SquadUIManager);

  @override
  _i11.SquadPersistenceManager get persistenceManager => (super.noSuchMethod(
        Invocation.getter(#persistenceManager),
        returnValue: _FakeSquadPersistenceManager_9(
          this,
          Invocation.getter(#persistenceManager),
        ),
        returnValueForMissingStub: _FakeSquadPersistenceManager_9(
          this,
          Invocation.getter(#persistenceManager),
        ),
      ) as _i11.SquadPersistenceManager);

  @override
  _i12.StateInitializer get stateInitializer => (super.noSuchMethod(
        Invocation.getter(#stateInitializer),
        returnValue: _FakeStateInitializer_10(
          this,
          Invocation.getter(#stateInitializer),
        ),
        returnValueForMissingStub: _FakeStateInitializer_10(
          this,
          Invocation.getter(#stateInitializer),
        ),
      ) as _i12.StateInitializer);

  @override
  _i13.TimerState get timerState => (super.noSuchMethod(
        Invocation.getter(#timerState),
        returnValue: _FakeTimerState_11(
          this,
          Invocation.getter(#timerState),
        ),
        returnValueForMissingStub: _FakeTimerState_11(
          this,
          Invocation.getter(#timerState),
        ),
      ) as _i13.TimerState);

  @override
  _i14.SquadPersistenceService get persistenceService => (super.noSuchMethod(
        Invocation.getter(#persistenceService),
        returnValue: _FakeSquadPersistenceService_12(
          this,
          Invocation.getter(#persistenceService),
        ),
        returnValueForMissingStub: _FakeSquadPersistenceService_12(
          this,
          Invocation.getter(#persistenceService),
        ),
      ) as _i14.SquadPersistenceService);

  @override
  _i15.NotificationCoordinator get notificationCoordinator =>
      (super.noSuchMethod(
        Invocation.getter(#notificationCoordinator),
        returnValue: _FakeNotificationCoordinator_13(
          this,
          Invocation.getter(#notificationCoordinator),
        ),
        returnValueForMissingStub: _FakeNotificationCoordinator_13(
          this,
          Invocation.getter(#notificationCoordinator),
        ),
      ) as _i15.NotificationCoordinator);

  @override
  _i16.LobbyService get lobbyService => (super.noSuchMethod(
        Invocation.getter(#lobbyService),
        returnValue: _FakeLobbyService_14(
          this,
          Invocation.getter(#lobbyService),
        ),
        returnValueForMissingStub: _FakeLobbyService_14(
          this,
          Invocation.getter(#lobbyService),
        ),
      ) as _i16.LobbyService);

  @override
  _i17.PeacockService get peacockService => (super.noSuchMethod(
        Invocation.getter(#peacockService),
        returnValue: _FakePeacockService_15(
          this,
          Invocation.getter(#peacockService),
        ),
        returnValueForMissingStub: _FakePeacockService_15(
          this,
          Invocation.getter(#peacockService),
        ),
      ) as _i17.PeacockService);

  @override
  _i18.AchievementService get achievementService => (super.noSuchMethod(
        Invocation.getter(#achievementService),
        returnValue: _FakeAchievementService_16(
          this,
          Invocation.getter(#achievementService),
        ),
        returnValueForMissingStub: _FakeAchievementService_16(
          this,
          Invocation.getter(#achievementService),
        ),
      ) as _i18.AchievementService);

  @override
  _i19.SquadMembershipService get squadMembershipService => (super.noSuchMethod(
        Invocation.getter(#squadMembershipService),
        returnValue: _FakeSquadMembershipService_17(
          this,
          Invocation.getter(#squadMembershipService),
        ),
        returnValueForMissingStub: _FakeSquadMembershipService_17(
          this,
          Invocation.getter(#squadMembershipService),
        ),
      ) as _i19.SquadMembershipService);

  @override
  _i20.SpotManagementService get spotManagementService => (super.noSuchMethod(
        Invocation.getter(#spotManagementService),
        returnValue: _FakeSpotManagementService_18(
          this,
          Invocation.getter(#spotManagementService),
        ),
        returnValueForMissingStub: _FakeSpotManagementService_18(
          this,
          Invocation.getter(#spotManagementService),
        ),
      ) as _i20.SpotManagementService);

  @override
  _i21.ChatService get chatService => (super.noSuchMethod(
        Invocation.getter(#chatService),
        returnValue: _FakeChatService_19(
          this,
          Invocation.getter(#chatService),
        ),
        returnValueForMissingStub: _FakeChatService_19(
          this,
          Invocation.getter(#chatService),
        ),
      ) as _i21.ChatService);

  @override
  _i22.AuthService get authService => (super.noSuchMethod(
        Invocation.getter(#authService),
        returnValue: _FakeAuthService_20(
          this,
          Invocation.getter(#authService),
        ),
        returnValueForMissingStub: _FakeAuthService_20(
          this,
          Invocation.getter(#authService),
        ),
      ) as _i22.AuthService);

  @override
  _i22.AudioService get audioService => (super.noSuchMethod(
        Invocation.getter(#audioService),
        returnValue: _FakeAudioService_21(
          this,
          Invocation.getter(#audioService),
        ),
        returnValueForMissingStub: _FakeAudioService_21(
          this,
          Invocation.getter(#audioService),
        ),
      ) as _i22.AudioService);

  @override
  _i22.CacheService get cacheService => (super.noSuchMethod(
        Invocation.getter(#cacheService),
        returnValue: _FakeCacheService_22(
          this,
          Invocation.getter(#cacheService),
        ),
        returnValueForMissingStub: _FakeCacheService_22(
          this,
          Invocation.getter(#cacheService),
        ),
      ) as _i22.CacheService);

  @override
  List<String?> get squadSpots => (super.noSuchMethod(
        Invocation.getter(#squadSpots),
        returnValue: <String?>[],
        returnValueForMissingStub: <String?>[],
      ) as List<String?>);

  @override
  List<Map<String, dynamic>?> get spotTimers => (super.noSuchMethod(
        Invocation.getter(#spotTimers),
        returnValue: <Map<String, dynamic>?>[],
        returnValueForMissingStub: <Map<String, dynamic>?>[],
      ) as List<Map<String, dynamic>?>);

  @override
  Map<String, String> get statuses => (super.noSuchMethod(
        Invocation.getter(#statuses),
        returnValue: <String, String>{},
        returnValueForMissingStub: <String, String>{},
      ) as Map<String, String>);

  @override
  List<String> get squadMembers => (super.noSuchMethod(
        Invocation.getter(#squadMembers),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);

  @override
  bool get isCreator => (super.noSuchMethod(
        Invocation.getter(#isCreator),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set context(_i28.BuildContext? _context) => super.noSuchMethod(
        Invocation.setter(
          #context,
          _context,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i29.Stream<_i23.SquadStateData> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i29.Stream<_i23.SquadStateData>.empty(),
        returnValueForMissingStub: _i29.Stream<_i23.SquadStateData>.empty(),
      ) as _i29.Stream<_i23.SquadStateData>);

  @override
  _i23.SquadStateData get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeSquadStateData_23(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeSquadStateData_23(
          this,
          Invocation.getter(#state),
        ),
      ) as _i23.SquadStateData);

  @override
  _i23.SquadStateData get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _FakeSquadStateData_23(
          this,
          Invocation.getter(#debugState),
        ),
        returnValueForMissingStub: _FakeSquadStateData_23(
          this,
          Invocation.getter(#debugState),
        ),
      ) as _i23.SquadStateData);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set onError(_i24.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set state(_i23.SquadStateData? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getDisplayNameForUid(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #getDisplayNameForUid,
          [uid],
        ),
        returnValue: _i30.dummyValue<String>(
          this,
          Invocation.method(
            #getDisplayNameForUid,
            [uid],
          ),
        ),
        returnValueForMissingStub: _i30.dummyValue<String>(
          this,
          Invocation.method(
            #getDisplayNameForUid,
            [uid],
          ),
        ),
      ) as String);

  @override
  String? getUidForDisplayName(String? displayName) => (super.noSuchMethod(
        Invocation.method(
          #getUidForDisplayName,
          [displayName],
        ),
        returnValueForMissingStub: null,
      ) as String?);

  @override
  _i29.Future<void> initialize(_i28.BuildContext? ctx) => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [ctx],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<String> createSquad(String? name) => (super.noSuchMethod(
        Invocation.method(
          #createSquad,
          [name],
        ),
        returnValue: _i29.Future<String>.value(_i30.dummyValue<String>(
          this,
          Invocation.method(
            #createSquad,
            [name],
          ),
        )),
        returnValueForMissingStub:
            _i29.Future<String>.value(_i30.dummyValue<String>(
          this,
          Invocation.method(
            #createSquad,
            [name],
          ),
        )),
      ) as _i29.Future<String>);

  @override
  _i29.Future<bool> joinSquad(String? code) => (super.noSuchMethod(
        Invocation.method(
          #joinSquad,
          [code],
        ),
        returnValue: _i29.Future<bool>.value(false),
        returnValueForMissingStub: _i29.Future<bool>.value(false),
      ) as _i29.Future<bool>);

  @override
  _i29.Future<void> leaveSquad() => (super.noSuchMethod(
        Invocation.method(
          #leaveSquad,
          [],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Stream<List<Map<String, dynamic>>> getActivePeacockAlerts(
          String? gameName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActivePeacockAlerts,
          [gameName],
        ),
        returnValue: _i29.Stream<List<Map<String, dynamic>>>.empty(),
        returnValueForMissingStub:
            _i29.Stream<List<Map<String, dynamic>>>.empty(),
      ) as _i29.Stream<List<Map<String, dynamic>>>);

  @override
  void clearNotifications(int? tabIndex) => super.noSuchMethod(
        Invocation.method(
          #clearNotifications,
          [tabIndex],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateTiltEnabled(bool? value) => super.noSuchMethod(
        Invocation.method(
          #updateTiltEnabled,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateProfileImage(String? url) => super.noSuchMethod(
        Invocation.method(
          #updateProfileImage,
          [url],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateDisplayName(String? name) => super.noSuchMethod(
        Invocation.method(
          #updateDisplayName,
          [name],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void callSpotForGame(
    int? spot,
    String? gameName,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #callSpotForGame,
          [
            spot,
            gameName,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i29.Future<void> loadSquadData(String? squadId) => (super.noSuchMethod(
        Invocation.method(
          #loadSquadData,
          [squadId],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  void updateSpotTimers(
    String? gameName,
    List<Map<String, dynamic>?>? timers,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateSpotTimers,
          [
            gameName,
            timers,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i29.Future<void> assignSpot(
    String? gameName,
    int? spotIndex,
    String? uid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #assignSpot,
          [
            gameName,
            spotIndex,
            uid,
          ],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> removeSpot(
    String? gameName,
    int? spotIndex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeSpot,
          [
            gameName,
            spotIndex,
          ],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> claimSpot(
    String? gameName,
    int? spotIndex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #claimSpot,
          [
            gameName,
            spotIndex,
          ],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> lockSpot(
    String? gameName,
    int? spotIndex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #lockSpot,
          [
            gameName,
            spotIndex,
          ],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i23.SquadStateData? old,
    _i23.SquadStateData? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i24.RemoveListener addListener(
    _i31.Listener<_i23.SquadStateData>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
        returnValueForMissingStub: () {},
      ) as _i24.RemoveListener);
}

/// A class which mocks [ChatStateNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatStateNotifier extends _i1.Mock implements _i25.ChatStateNotifier {
  @override
  _i24.Ref<Object?> get ref => (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeRef_24<Object?>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub: _FakeRef_24<Object?>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i24.Ref<Object?>);

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i29.Stream<_i25.ChatStateData> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i29.Stream<_i25.ChatStateData>.empty(),
        returnValueForMissingStub: _i29.Stream<_i25.ChatStateData>.empty(),
      ) as _i29.Stream<_i25.ChatStateData>);

  @override
  _i25.ChatStateData get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeChatStateData_25(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeChatStateData_25(
          this,
          Invocation.getter(#state),
        ),
      ) as _i25.ChatStateData);

  @override
  _i25.ChatStateData get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _FakeChatStateData_25(
          this,
          Invocation.getter(#debugState),
        ),
        returnValueForMissingStub: _FakeChatStateData_25(
          this,
          Invocation.getter(#debugState),
        ),
      ) as _i25.ChatStateData);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set onError(_i24.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set state(_i25.ChatStateData? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void init() => super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void startRecording() => super.noSuchMethod(
        Invocation.method(
          #startRecording,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopRecording() => super.noSuchMethod(
        Invocation.method(
          #stopRecording,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateTyping(
    String? userId,
    bool? isTyping,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateTyping,
          [
            userId,
            isTyping,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void loadMessages(String? chatGroupId) => super.noSuchMethod(
        Invocation.method(
          #loadMessages,
          [chatGroupId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void paginateMore() => super.noSuchMethod(
        Invocation.method(
          #paginateMore,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateSendingStatus(
    String? id,
    bool? status,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateSendingStatus,
          [
            id,
            status,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeSendingStatus(String? id) => super.noSuchMethod(
        Invocation.method(
          #removeSendingStatus,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearReplyToMessage() => super.noSuchMethod(
        Invocation.method(
          #clearReplyToMessage,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setReplyToMessage(Map<String, dynamic>? message) => super.noSuchMethod(
        Invocation.method(
          #setReplyToMessage,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i29.Future<void> sendMessage(_i32.Message? message) => (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [message],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  void handleOfflineSync() => super.noSuchMethod(
        Invocation.method(
          #handleOfflineSync,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleMessageReactions(
    String? messageId,
    String? reaction,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #handleMessageReactions,
          [
            messageId,
            reaction,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void startTyping() => super.noSuchMethod(
        Invocation.method(
          #startTyping,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i25.ChatStateData? old,
    _i25.ChatStateData? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i24.RemoveListener addListener(
    _i31.Listener<_i25.ChatStateData>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
        returnValueForMissingStub: () {},
      ) as _i24.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ReactionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockReactionService extends _i1.Mock implements _i33.ReactionService {
  @override
  _i29.Future<void> addReaction({
    required String? chatGroupId,
    required String? messageId,
    required String? emoji,
    required _i34.ChatType? chatType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addReaction,
          [],
          {
            #chatGroupId: chatGroupId,
            #messageId: messageId,
            #emoji: emoji,
            #chatType: chatType,
          },
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> removeReaction({
    required String? chatGroupId,
    required String? messageId,
    required String? emoji,
    required _i34.ChatType? chatType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeReaction,
          [],
          {
            #chatGroupId: chatGroupId,
            #messageId: messageId,
            #emoji: emoji,
            #chatType: chatType,
          },
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Stream<Map<String, List<String>>> getMessageReactions({
    required String? chatGroupId,
    required String? messageId,
    required _i34.ChatType? chatType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessageReactions,
          [],
          {
            #chatGroupId: chatGroupId,
            #messageId: messageId,
            #chatType: chatType,
          },
        ),
        returnValue: _i29.Stream<Map<String, List<String>>>.empty(),
        returnValueForMissingStub:
            _i29.Stream<Map<String, List<String>>>.empty(),
      ) as _i29.Stream<Map<String, List<String>>>);

  @override
  _i29.Future<bool> hasUserReacted({
    required String? chatGroupId,
    required String? messageId,
    required String? emoji,
    required _i34.ChatType? chatType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasUserReacted,
          [],
          {
            #chatGroupId: chatGroupId,
            #messageId: messageId,
            #emoji: emoji,
            #chatType: chatType,
          },
        ),
        returnValue: _i29.Future<bool>.value(false),
        returnValueForMissingStub: _i29.Future<bool>.value(false),
      ) as _i29.Future<bool>);
}

/// A class which mocks [SQLiteHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockSQLiteHelper extends _i1.Mock implements _i35.SQLiteHelper {
  @override
  _i29.Future<_i26.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i29.Future<_i26.Database>.value(_FakeDatabase_26(
          this,
          Invocation.getter(#database),
        )),
        returnValueForMissingStub:
            _i29.Future<_i26.Database>.value(_FakeDatabase_26(
          this,
          Invocation.getter(#database),
        )),
      ) as _i29.Future<_i26.Database>);

  @override
  _i29.Future<void> insertMessage(
    Map<String, dynamic>? message, {
    String? chatGroupId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertMessage,
          [message],
          {#chatGroupId: chatGroupId},
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> updateMessage(
    String? msgId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMessage,
          [
            msgId,
            updates,
          ],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> clearMessages({String? chatGroupId}) => (super.noSuchMethod(
        Invocation.method(
          #clearMessages,
          [],
          {#chatGroupId: chatGroupId},
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<List<Map<String, dynamic>>> getMessages(
    int? offset,
    int? limit, {
    String? chatGroupId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessages,
          [
            offset,
            limit,
          ],
          {#chatGroupId: chatGroupId},
        ),
        returnValue: _i29.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub:
            _i29.Future<List<Map<String, dynamic>>>.value(
                <Map<String, dynamic>>[]),
      ) as _i29.Future<List<Map<String, dynamic>>>);

  @override
  _i29.Future<List<Map<String, dynamic>>> getCachedGroups(
    String? gameName,
    String? searchTerm,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedGroups,
          [
            gameName,
            searchTerm,
          ],
        ),
        returnValue: _i29.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub:
            _i29.Future<List<Map<String, dynamic>>>.value(
                <Map<String, dynamic>>[]),
      ) as _i29.Future<List<Map<String, dynamic>>>);

  @override
  _i29.Future<void> cacheGroups(
    List<Map<String, dynamic>>? groups,
    String? gameName,
    String? searchTerm,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheGroups,
          [
            groups,
            gameName,
            searchTerm,
          ],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);
}

/// A class which mocks [UserManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserManager extends _i1.Mock implements _i5.UserManager {
  @override
  Map<String, String?> get memberProfileImages => (super.noSuchMethod(
        Invocation.getter(#memberProfileImages),
        returnValue: <String, String?>{},
        returnValueForMissingStub: <String, String?>{},
      ) as Map<String, String?>);

  @override
  Map<String, String?> get preferredModes => (super.noSuchMethod(
        Invocation.getter(#preferredModes),
        returnValue: <String, String?>{},
        returnValueForMissingStub: <String, String?>{},
      ) as Map<String, String?>);

  @override
  Map<String, Map<String, bool>> get userBlocks => (super.noSuchMethod(
        Invocation.getter(#userBlocks),
        returnValue: <String, Map<String, bool>>{},
        returnValueForMissingStub: <String, Map<String, bool>>{},
      ) as Map<String, Map<String, bool>>);

  @override
  List<String> get alertCircles => (super.noSuchMethod(
        Invocation.getter(#alertCircles),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);

  @override
  List<Map<String, dynamic>> get pinnedGames => (super.noSuchMethod(
        Invocation.getter(#pinnedGames),
        returnValue: <Map<String, dynamic>>[],
        returnValueForMissingStub: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  Set<String> get mutedGames => (super.noSuchMethod(
        Invocation.getter(#mutedGames),
        returnValue: <String>{},
        returnValueForMissingStub: <String>{},
      ) as Set<String>);

  @override
  Map<String, bool> get hasRatedGame => (super.noSuchMethod(
        Invocation.getter(#hasRatedGame),
        returnValue: <String, bool>{},
        returnValueForMissingStub: <String, bool>{},
      ) as Map<String, bool>);

  @override
  set memberProfileImages(Map<String, String?>? _memberProfileImages) =>
      super.noSuchMethod(
        Invocation.setter(
          #memberProfileImages,
          _memberProfileImages,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set preferredModes(Map<String, String?>? _preferredModes) =>
      super.noSuchMethod(
        Invocation.setter(
          #preferredModes,
          _preferredModes,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set userBlocks(Map<String, Map<String, bool>>? _userBlocks) =>
      super.noSuchMethod(
        Invocation.setter(
          #userBlocks,
          _userBlocks,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set alertCircles(List<String>? _alertCircles) => super.noSuchMethod(
        Invocation.setter(
          #alertCircles,
          _alertCircles,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set pinnedGames(List<Map<String, dynamic>>? _pinnedGames) =>
      super.noSuchMethod(
        Invocation.setter(
          #pinnedGames,
          _pinnedGames,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set mutedGames(Set<String>? _mutedGames) => super.noSuchMethod(
        Invocation.setter(
          #mutedGames,
          _mutedGames,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set hasRatedGame(Map<String, bool>? _hasRatedGame) => super.noSuchMethod(
        Invocation.setter(
          #hasRatedGame,
          _hasRatedGame,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void updateProfileImage(String? url) => super.noSuchMethod(
        Invocation.method(
          #updateProfileImage,
          [url],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateDisplayName(String? name) => super.noSuchMethod(
        Invocation.method(
          #updateDisplayName,
          [name],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updatePreferredMode(
    String? user,
    String? mode,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updatePreferredMode,
          [
            user,
            mode,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isUserBlocked(String? user) => (super.noSuchMethod(
        Invocation.method(
          #isUserBlocked,
          [user],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i29.Future<void> updateUserProfile(
    String? uid,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [
            uid,
            data,
          ],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<Map<String, dynamic>?> getUserProfile(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [uid],
        ),
        returnValue: _i29.Future<Map<String, dynamic>?>.value(),
        returnValueForMissingStub: _i29.Future<Map<String, dynamic>?>.value(),
      ) as _i29.Future<Map<String, dynamic>?>);

  @override
  String getDisplayNameForUid(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #getDisplayNameForUid,
          [uid],
        ),
        returnValue: _i30.dummyValue<String>(
          this,
          Invocation.method(
            #getDisplayNameForUid,
            [uid],
          ),
        ),
        returnValueForMissingStub: _i30.dummyValue<String>(
          this,
          Invocation.method(
            #getDisplayNameForUid,
            [uid],
          ),
        ),
      ) as String);

  @override
  _i29.Future<Map<String, dynamic>?> getCachedSenderDetails(String? senderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedSenderDetails,
          [senderId],
        ),
        returnValue: _i29.Future<Map<String, dynamic>?>.value(),
        returnValueForMissingStub: _i29.Future<Map<String, dynamic>?>.value(),
      ) as _i29.Future<Map<String, dynamic>?>);

  @override
  _i29.Future<void> blockUser(
    String? blockerUid,
    String? blockedUid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #blockUser,
          [
            blockerUid,
            blockedUid,
          ],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> unblockUser(
    String? blockerUid,
    String? blockedUid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unblockUser,
          [
            blockerUid,
            blockedUid,
          ],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<Map<String, bool>> getBlockedUsers(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBlockedUsers,
          [uid],
        ),
        returnValue: _i29.Future<Map<String, bool>>.value(<String, bool>{}),
        returnValueForMissingStub:
            _i29.Future<Map<String, bool>>.value(<String, bool>{}),
      ) as _i29.Future<Map<String, bool>>);

  @override
  void markGameAsRated(String? gameName) => super.noSuchMethod(
        Invocation.method(
          #markGameAsRated,
          [gameName],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i29.Future<void> fetchPinnedGames() => (super.noSuchMethod(
        Invocation.method(
          #fetchPinnedGames,
          [],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> addPinnedGame(Map<String, dynamic>? game) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPinnedGame,
          [game],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> removePinnedGame(String? gameName) => (super.noSuchMethod(
        Invocation.method(
          #removePinnedGame,
          [gameName],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> updateGameLastPlayed(String? gameName) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateGameLastPlayed,
          [gameName],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> fetchMutedGames() => (super.noSuchMethod(
        Invocation.method(
          #fetchMutedGames,
          [],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> muteGame(String? gameSlug) => (super.noSuchMethod(
        Invocation.method(
          #muteGame,
          [gameSlug],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> unmuteGame(String? gameSlug) => (super.noSuchMethod(
        Invocation.method(
          #unmuteGame,
          [gameSlug],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  bool isGameMuted(String? gameSlug) => (super.noSuchMethod(
        Invocation.method(
          #isGameMuted,
          [gameSlug],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i29.Future<void> clearMutedGames() => (super.noSuchMethod(
        Invocation.method(
          #clearMutedGames,
          [],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<List<Map<String, dynamic>>> searchUsers(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchUsers,
          [query],
        ),
        returnValue: _i29.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub:
            _i29.Future<List<Map<String, dynamic>>>.value(
                <Map<String, dynamic>>[]),
      ) as _i29.Future<List<Map<String, dynamic>>>);

  @override
  _i29.Future<String?> startDMThread(String? otherUserId) =>
      (super.noSuchMethod(
        Invocation.method(
          #startDMThread,
          [otherUserId],
        ),
        returnValue: _i29.Future<String?>.value(),
        returnValueForMissingStub: _i29.Future<String?>.value(),
      ) as _i29.Future<String?>);

  @override
  _i29.Stream<List<Map<String, dynamic>>> streamFriends() =>
      (super.noSuchMethod(
        Invocation.method(
          #streamFriends,
          [],
        ),
        returnValue: _i29.Stream<List<Map<String, dynamic>>>.empty(),
        returnValueForMissingStub:
            _i29.Stream<List<Map<String, dynamic>>>.empty(),
      ) as _i29.Stream<List<Map<String, dynamic>>>);

  @override
  _i29.Stream<List<Map<String, dynamic>>> streamPendingRequests() =>
      (super.noSuchMethod(
        Invocation.method(
          #streamPendingRequests,
          [],
        ),
        returnValue: _i29.Stream<List<Map<String, dynamic>>>.empty(),
        returnValueForMissingStub:
            _i29.Stream<List<Map<String, dynamic>>>.empty(),
      ) as _i29.Stream<List<Map<String, dynamic>>>);

  @override
  _i29.Future<void> acceptFriendRequest(String? requesterId) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptFriendRequest,
          [requesterId],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> declineFriendRequest(String? requesterId) =>
      (super.noSuchMethod(
        Invocation.method(
          #declineFriendRequest,
          [requesterId],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> sendFriendRequest(String? receiverId) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendFriendRequest,
          [receiverId],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> removeFriend(String? friendId) => (super.noSuchMethod(
        Invocation.method(
          #removeFriend,
          [friendId],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> submitFeedback({
    required String? type,
    required String? page,
    required String? content,
    required String? severity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitFeedback,
          [],
          {
            #type: type,
            #page: page,
            #content: content,
            #severity: severity,
          },
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<List<Map<String, dynamic>>> fetchPublicGroups() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchPublicGroups,
          [],
        ),
        returnValue: _i29.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub:
            _i29.Future<List<Map<String, dynamic>>>.value(
                <Map<String, dynamic>>[]),
      ) as _i29.Future<List<Map<String, dynamic>>>);

  @override
  _i29.Future<List<Map<String, dynamic>>> searchRelevantSquads(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchRelevantSquads,
          [query],
        ),
        returnValue: _i29.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub:
            _i29.Future<List<Map<String, dynamic>>>.value(
                <Map<String, dynamic>>[]),
      ) as _i29.Future<List<Map<String, dynamic>>>);

  @override
  void addListener(_i36.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i36.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Ref].
///
/// See the documentation for Mockito's code generation for more information.
class MockRef<State extends Object?> extends _i1.Mock
    implements _i24.Ref<State> {
  @override
  _i24.ProviderContainer get container => (super.noSuchMethod(
        Invocation.getter(#container),
        returnValue: _FakeProviderContainer_27(
          this,
          Invocation.getter(#container),
        ),
        returnValueForMissingStub: _FakeProviderContainer_27(
          this,
          Invocation.getter(#container),
        ),
      ) as _i24.ProviderContainer);

  @override
  T refresh<T>(_i24.Refreshable<T>? provider) => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [provider],
        ),
        returnValue: _i30.dummyValue<T>(
          this,
          Invocation.method(
            #refresh,
            [provider],
          ),
        ),
        returnValueForMissingStub: _i30.dummyValue<T>(
          this,
          Invocation.method(
            #refresh,
            [provider],
          ),
        ),
      ) as T);

  @override
  void invalidate(_i24.ProviderOrFamily? provider) => super.noSuchMethod(
        Invocation.method(
          #invalidate,
          [provider],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenSelf(
    void Function(
      State?,
      State,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void invalidateSelf() => super.noSuchMethod(
        Invocation.method(
          #invalidateSelf,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onAddListener(void Function()? cb) => super.noSuchMethod(
        Invocation.method(
          #onAddListener,
          [cb],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onRemoveListener(void Function()? cb) => super.noSuchMethod(
        Invocation.method(
          #onRemoveListener,
          [cb],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onResume(void Function()? cb) => super.noSuchMethod(
        Invocation.method(
          #onResume,
          [cb],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onCancel(void Function()? cb) => super.noSuchMethod(
        Invocation.method(
          #onCancel,
          [cb],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDispose(void Function()? cb) => super.noSuchMethod(
        Invocation.method(
          #onDispose,
          [cb],
        ),
        returnValueForMissingStub: null,
      );

  @override
  T read<T>(_i24.ProviderListenable<T>? provider) => (super.noSuchMethod(
        Invocation.method(
          #read,
          [provider],
        ),
        returnValue: _i30.dummyValue<T>(
          this,
          Invocation.method(
            #read,
            [provider],
          ),
        ),
        returnValueForMissingStub: _i30.dummyValue<T>(
          this,
          Invocation.method(
            #read,
            [provider],
          ),
        ),
      ) as T);

  @override
  bool exists(_i24.ProviderBase<Object?>? provider) => (super.noSuchMethod(
        Invocation.method(
          #exists,
          [provider],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  T watch<T>(_i24.ProviderListenable<T>? provider) => (super.noSuchMethod(
        Invocation.method(
          #watch,
          [provider],
        ),
        returnValue: _i30.dummyValue<T>(
          this,
          Invocation.method(
            #watch,
            [provider],
          ),
        ),
        returnValueForMissingStub: _i30.dummyValue<T>(
          this,
          Invocation.method(
            #watch,
            [provider],
          ),
        ),
      ) as T);

  @override
  _i24.KeepAliveLink keepAlive() => (super.noSuchMethod(
        Invocation.method(
          #keepAlive,
          [],
        ),
        returnValue: _FakeKeepAliveLink_28(
          this,
          Invocation.method(
            #keepAlive,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeKeepAliveLink_28(
          this,
          Invocation.method(
            #keepAlive,
            [],
          ),
        ),
      ) as _i24.KeepAliveLink);

  @override
  _i24.ProviderSubscription<T> listen<T>(
    _i24.ProviderListenable<T>? provider,
    void Function(
      T?,
      T,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
    bool? fireImmediately,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listen,
          [
            provider,
            listener,
          ],
          {
            #onError: onError,
            #fireImmediately: fireImmediately,
          },
        ),
        returnValue: _FakeProviderSubscription_29<T>(
          this,
          Invocation.method(
            #listen,
            [
              provider,
              listener,
            ],
            {
              #onError: onError,
              #fireImmediately: fireImmediately,
            },
          ),
        ),
        returnValueForMissingStub: _FakeProviderSubscription_29<T>(
          this,
          Invocation.method(
            #listen,
            [
              provider,
              listener,
            ],
            {
              #onError: onError,
              #fireImmediately: fireImmediately,
            },
          ),
        ),
      ) as _i24.ProviderSubscription<T>);
}

/// A class which mocks [ChatService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatService extends _i1.Mock implements _i21.ChatService {
  @override
  int get offlineMessageCount => (super.noSuchMethod(
        Invocation.getter(#offlineMessageCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool get isOnline => (super.noSuchMethod(
        Invocation.getter(#isOnline),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i29.Stream<_i37.QuerySnapshot<Object?>> getChatMessages(
    _i28.BuildContext? context, {
    String? chatGroupId,
    required _i34.ChatType? chatType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChatMessages,
          [context],
          {
            #chatGroupId: chatGroupId,
            #chatType: chatType,
          },
        ),
        returnValue: _i29.Stream<_i37.QuerySnapshot<Object?>>.empty(),
        returnValueForMissingStub:
            _i29.Stream<_i37.QuerySnapshot<Object?>>.empty(),
      ) as _i29.Stream<_i37.QuerySnapshot<Object?>>);

  @override
  _i29.Stream<String?> getTypingUser(
    _i28.BuildContext? context, {
    String? chatGroupId,
    required _i34.ChatType? chatType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTypingUser,
          [context],
          {
            #chatGroupId: chatGroupId,
            #chatType: chatType,
          },
        ),
        returnValue: _i29.Stream<String?>.empty(),
        returnValueForMissingStub: _i29.Stream<String?>.empty(),
      ) as _i29.Stream<String?>);

  @override
  _i29.Future<_i27.MessageSendResult> sendMessage(
    _i28.BuildContext? context, {
    required String? senderUid,
    String? text,
    String? imageUrl,
    String? videoUrl,
    String? audioUrl,
    List<Map<String, dynamic>>? photos = const [],
    List<Map<String, dynamic>>? videos = const [],
    List<Map<String, dynamic>>? audio = const [],
    List<Map<String, dynamic>>? reactions = const [],
    String? pollId,
    String? replyTo,
    String? chatGroupId,
    required _i34.ChatType? chatType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [context],
          {
            #senderUid: senderUid,
            #text: text,
            #imageUrl: imageUrl,
            #videoUrl: videoUrl,
            #audioUrl: audioUrl,
            #photos: photos,
            #videos: videos,
            #audio: audio,
            #reactions: reactions,
            #pollId: pollId,
            #replyTo: replyTo,
            #chatGroupId: chatGroupId,
            #chatType: chatType,
          },
        ),
        returnValue:
            _i29.Future<_i27.MessageSendResult>.value(_FakeMessageSendResult_30(
          this,
          Invocation.method(
            #sendMessage,
            [context],
            {
              #senderUid: senderUid,
              #text: text,
              #imageUrl: imageUrl,
              #videoUrl: videoUrl,
              #audioUrl: audioUrl,
              #photos: photos,
              #videos: videos,
              #audio: audio,
              #reactions: reactions,
              #pollId: pollId,
              #replyTo: replyTo,
              #chatGroupId: chatGroupId,
              #chatType: chatType,
            },
          ),
        )),
        returnValueForMissingStub:
            _i29.Future<_i27.MessageSendResult>.value(_FakeMessageSendResult_30(
          this,
          Invocation.method(
            #sendMessage,
            [context],
            {
              #senderUid: senderUid,
              #text: text,
              #imageUrl: imageUrl,
              #videoUrl: videoUrl,
              #audioUrl: audioUrl,
              #photos: photos,
              #videos: videos,
              #audio: audio,
              #reactions: reactions,
              #pollId: pollId,
              #replyTo: replyTo,
              #chatGroupId: chatGroupId,
              #chatType: chatType,
            },
          ),
        )),
      ) as _i29.Future<_i27.MessageSendResult>);

  @override
  _i29.Future<String> uploadMedia(
    _i38.File? file,
    String? fileName,
    bool? isVideo,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadMedia,
          [
            file,
            fileName,
            isVideo,
          ],
        ),
        returnValue: _i29.Future<String>.value(_i30.dummyValue<String>(
          this,
          Invocation.method(
            #uploadMedia,
            [
              file,
              fileName,
              isVideo,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i29.Future<String>.value(_i30.dummyValue<String>(
          this,
          Invocation.method(
            #uploadMedia,
            [
              file,
              fileName,
              isVideo,
            ],
          ),
        )),
      ) as _i29.Future<String>);

  @override
  _i29.Future<String> uploadAudio(
    _i38.File? file,
    String? fileName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadAudio,
          [
            file,
            fileName,
          ],
        ),
        returnValue: _i29.Future<String>.value(_i30.dummyValue<String>(
          this,
          Invocation.method(
            #uploadAudio,
            [
              file,
              fileName,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i29.Future<String>.value(_i30.dummyValue<String>(
          this,
          Invocation.method(
            #uploadAudio,
            [
              file,
              fileName,
            ],
          ),
        )),
      ) as _i29.Future<String>);

  @override
  _i29.Future<void> markAsDelivered(String? docId) => (super.noSuchMethod(
        Invocation.method(
          #markAsDelivered,
          [docId],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> updateTypingStatus(
    _i28.BuildContext? context,
    String? user,
    bool? isTyping, {
    String? chatGroupId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTypingStatus,
          [
            context,
            user,
            isTyping,
          ],
          {#chatGroupId: chatGroupId},
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> addReaction(
    _i28.BuildContext? context,
    String? msgId,
    String? reaction, {
    String? chatGroupId,
    _i34.ChatType? chatType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addReaction,
          [
            context,
            msgId,
            reaction,
          ],
          {
            #chatGroupId: chatGroupId,
            #chatType: chatType,
          },
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<List<Map<String, dynamic>>> loadMoreMessages({
    required int? offset,
    required int? limit,
    String? chatGroupId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadMoreMessages,
          [],
          {
            #offset: offset,
            #limit: limit,
            #chatGroupId: chatGroupId,
          },
        ),
        returnValue: _i29.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub:
            _i29.Future<List<Map<String, dynamic>>>.value(
                <Map<String, dynamic>>[]),
      ) as _i29.Future<List<Map<String, dynamic>>>);

  @override
  _i29.Future<List<Map<String, dynamic>>> getCachedMessages(
    int? offset,
    int? limit, {
    String? chatGroupId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedMessages,
          [
            offset,
            limit,
          ],
          {#chatGroupId: chatGroupId},
        ),
        returnValue: _i29.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub:
            _i29.Future<List<Map<String, dynamic>>>.value(
                <Map<String, dynamic>>[]),
      ) as _i29.Future<List<Map<String, dynamic>>>);

  @override
  _i29.Future<void> retryOfflineMessages() => (super.noSuchMethod(
        Invocation.method(
          #retryOfflineMessages,
          [],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> cacheMessagesFromSnapshot(
    _i37.QuerySnapshot<Object?>? snapshot,
    String? chatGroupId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheMessagesFromSnapshot,
          [
            snapshot,
            chatGroupId,
          ],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> sendReply(
    String? messageId,
    String? text,
    String? squadId, {
    String? chatGroupId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendReply,
          [
            messageId,
            text,
            squadId,
          ],
          {#chatGroupId: chatGroupId},
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> deleteMessage(
    String? messageId,
    String? squadId, {
    String? chatGroupId,
    required _i34.ChatType? chatType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMessage,
          [
            messageId,
            squadId,
          ],
          {
            #chatGroupId: chatGroupId,
            #chatType: chatType,
          },
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> editMessage(
    String? messageId,
    String? newText,
    String? squadId, {
    String? chatGroupId,
    required _i34.ChatType? chatType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #editMessage,
          [
            messageId,
            newText,
            squadId,
          ],
          {
            #chatGroupId: chatGroupId,
            #chatType: chatType,
          },
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> pinMessage(
    String? messageId,
    String? chatGroupId,
    _i34.ChatType? chatType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #pinMessage,
          [
            messageId,
            chatGroupId,
            chatType,
          ],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> unpinMessage(
    String? messageId,
    String? chatGroupId,
    _i34.ChatType? chatType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unpinMessage,
          [
            messageId,
            chatGroupId,
            chatType,
          ],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<void> bumpMessage(
    String? messageId,
    String? chatGroupId,
    _i34.ChatType? chatType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #bumpMessage,
          [
            messageId,
            chatGroupId,
            chatType,
          ],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  _i29.Future<_i39.MessageData?> getMessageById(
    String? messageId, {
    String? chatGroupId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessageById,
          [messageId],
          {#chatGroupId: chatGroupId},
        ),
        returnValue: _i29.Future<_i39.MessageData?>.value(),
        returnValueForMissingStub: _i29.Future<_i39.MessageData?>.value(),
      ) as _i29.Future<_i39.MessageData?>);
}
