// Mocks generated by Mockito 5.4.6 from annotations
// in squad_sync/test/timer_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i3;
import 'package:squad_sync/chat/sqlite_helper.dart' as _i5;
import 'package:squad_sync/services/firestore_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeQueryBuilder_0 extends _i1.SmartFake implements _i2.QueryBuilder {
  _FakeQueryBuilder_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabase_1 extends _i1.SmartFake implements _i3.Database {
  _FakeDatabase_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i2.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.QueryBuilder get queryBuilder => (super.noSuchMethod(
        Invocation.getter(#queryBuilder),
        returnValue: _FakeQueryBuilder_0(
          this,
          Invocation.getter(#queryBuilder),
        ),
      ) as _i2.QueryBuilder);

  @override
  void registerField<T>(_i2.FirestoreFieldSerializer<T>? serializer) =>
      super.noSuchMethod(
        Invocation.method(
          #registerField,
          [serializer],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void markFieldChanged(String? fieldName) => super.noSuchMethod(
        Invocation.method(
          #markFieldChanged,
          [fieldName],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> updateFirestore({
    required Map<String, String>? displayNameCache,
    bool? force = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFirestore,
          [],
          {
            #displayNameCache: displayNameCache,
            #force: force,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveGameSearch(
    String? query,
    Map<String, dynamic>? gameData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveGameSearch,
          [
            query,
            gameData,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> loadFirestoreData(
          {required Map<String, String>? displayNameCache}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadFirestoreData,
          [],
          {#displayNameCache: displayNameCache},
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>?> loadFirestore(
    String? collection,
    String? document,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadFirestore,
          [
            collection,
            document,
          ],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Stream<Map<String, dynamic>?> getVoiceRoomStream(String? roomId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVoiceRoomStream,
          [roomId],
        ),
        returnValue: _i4.Stream<Map<String, dynamic>?>.empty(),
      ) as _i4.Stream<Map<String, dynamic>?>);

  @override
  _i4.Future<void> updateVoiceRoom(
    String? roomId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateVoiceRoom,
          [
            roomId,
            data,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateVoiceParticipant(
    String? roomId,
    String? uid,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateVoiceParticipant,
          [
            roomId,
            uid,
            data,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [SQLiteHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockSQLiteHelper extends _i1.Mock implements _i5.SQLiteHelper {
  MockSQLiteHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i3.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i4.Future<_i3.Database>.value(_FakeDatabase_1(
          this,
          Invocation.getter(#database),
        )),
      ) as _i4.Future<_i3.Database>);

  @override
  _i4.Future<void> insertMessage(
    Map<String, dynamic>? message, {
    String? chatGroupId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertMessage,
          [message],
          {#chatGroupId: chatGroupId},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateMessage(
    String? msgId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMessage,
          [
            msgId,
            updates,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearMessages({String? chatGroupId}) => (super.noSuchMethod(
        Invocation.method(
          #clearMessages,
          [],
          {#chatGroupId: chatGroupId},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getMessages(
    int? offset,
    int? limit, {
    String? chatGroupId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessages,
          [
            offset,
            limit,
          ],
          {#chatGroupId: chatGroupId},
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getCachedGroups(
    String? gameName,
    String? searchTerm,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedGroups,
          [
            gameName,
            searchTerm,
          ],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> cacheGroups(
    List<Map<String, dynamic>>? groups,
    String? gameName,
    String? searchTerm,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheGroups,
          [
            groups,
            gameName,
            searchTerm,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getCachedGames(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedGames,
          [query],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> cacheGames(
    List<Map<String, dynamic>>? games,
    String? query,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheGames,
          [
            games,
            query,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> getCacheMetadata(String? cacheKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCacheMetadata,
          [cacheKey],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> insertCacheMetadata(
    String? cacheKey,
    int? timestamp,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertCacheMetadata,
          [
            cacheKey,
            timestamp,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cleanupExpiredCache(Duration? ttl) => (super.noSuchMethod(
        Invocation.method(
          #cleanupExpiredCache,
          [ttl],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cacheVoiceRoom(
    String? roomId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheVoiceRoom,
          [
            roomId,
            data,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> getCachedVoiceRoom(String? roomId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedVoiceRoom,
          [roomId],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);
}
