// Mocks generated by Mockito 5.4.6 from annotations
// in squad_sync/test/timer_management_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:squad_sync/domain/entities/lobby.dart' as _i2;
import 'package:squad_sync/domain/entities/lobby_state.dart' as _i3;
import 'package:squad_sync/domain/repositories/lobby_repository.dart' as _i5;
import 'package:squad_sync/services/timer_service.dart' as _i7;
import 'package:state_notifier/state_notifier.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLobby_0 extends _i1.SmartFake implements _i2.Lobby {
  _FakeLobby_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLobbyState_1 extends _i1.SmartFake implements _i3.LobbyState {
  _FakeLobbyState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAsyncValue_2<T> extends _i1.SmartFake implements _i4.AsyncValue<T> {
  _FakeAsyncValue_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_3 extends _i1.SmartFake implements Duration {
  _FakeDuration_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LobbyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLobbyRepository extends _i1.Mock implements _i5.LobbyRepository {
  MockLobbyRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Lobby> createLobby(
    String? name,
    String? gameName,
    int? maxSpots,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLobby,
          [
            name,
            gameName,
            maxSpots,
          ],
        ),
        returnValue: _i6.Future<_i2.Lobby>.value(_FakeLobby_0(
          this,
          Invocation.method(
            #createLobby,
            [
              name,
              gameName,
              maxSpots,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Lobby>);

  @override
  _i6.Future<_i2.Lobby?> getLobby(String? lobbyId) => (super.noSuchMethod(
        Invocation.method(
          #getLobby,
          [lobbyId],
        ),
        returnValue: _i6.Future<_i2.Lobby?>.value(),
      ) as _i6.Future<_i2.Lobby?>);

  @override
  _i6.Future<_i2.Lobby?> getLobbyByInviteCode(String? inviteCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLobbyByInviteCode,
          [inviteCode],
        ),
        returnValue: _i6.Future<_i2.Lobby?>.value(),
      ) as _i6.Future<_i2.Lobby?>);

  @override
  _i6.Future<List<_i2.Lobby>> getUserLobbies(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserLobbies,
          [userId],
        ),
        returnValue: _i6.Future<List<_i2.Lobby>>.value(<_i2.Lobby>[]),
      ) as _i6.Future<List<_i2.Lobby>>);

  @override
  _i6.Future<void> deleteLobby(String? lobbyId) => (super.noSuchMethod(
        Invocation.method(
          #deleteLobby,
          [lobbyId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> joinLobby(
    String? lobbyId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #joinLobby,
          [
            lobbyId,
            userId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> leaveLobby(
    String? lobbyId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #leaveLobby,
          [
            lobbyId,
            userId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> kickMember(
    String? lobbyId,
    String? memberId,
    String? kickedBy,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #kickMember,
          [
            lobbyId,
            memberId,
            kickedBy,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> assignSpot(
    String? lobbyId,
    int? spotIndex,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #assignSpot,
          [
            lobbyId,
            spotIndex,
            userId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> startSpotTimer(
    String? lobbyId,
    int? spotIndex,
    Duration? duration,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #startSpotTimer,
          [
            lobbyId,
            spotIndex,
            duration,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> cancelSpotTimer(
    String? lobbyId,
    int? spotIndex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelSpotTimer,
          [
            lobbyId,
            spotIndex,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> processExpiredTimers() => (super.noSuchMethod(
        Invocation.method(
          #processExpiredTimers,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Stream<Map<String, Duration>> getSpotTimerStates(String? lobbyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSpotTimerStates,
          [lobbyId],
        ),
        returnValue: _i6.Stream<Map<String, Duration>>.empty(),
      ) as _i6.Stream<Map<String, Duration>>);

  @override
  _i6.Stream<Map<String, Duration>> getPeacockTimerStates() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPeacockTimerStates,
          [],
        ),
        returnValue: _i6.Stream<Map<String, Duration>>.empty(),
      ) as _i6.Stream<Map<String, Duration>>);

  @override
  _i6.Future<void> addToPeacockQueue(
    String? userId,
    String? gameName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToPeacockQueue,
          [
            userId,
            gameName,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> removeFromPeacockQueue(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromPeacockQueue,
          [userId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> processPeacockQueue() => (super.noSuchMethod(
        Invocation.method(
          #processPeacockQueue,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateMemberStatus(
    String? lobbyId,
    String? userId,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMemberStatus,
          [
            lobbyId,
            userId,
            status,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateGlobalStatus(
    String? userId,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateGlobalStatus,
          [
            userId,
            status,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i3.LobbyState> loadLobbyState() => (super.noSuchMethod(
        Invocation.method(
          #loadLobbyState,
          [],
        ),
        returnValue: _i6.Future<_i3.LobbyState>.value(_FakeLobbyState_1(
          this,
          Invocation.method(
            #loadLobbyState,
            [],
          ),
        )),
      ) as _i6.Future<_i3.LobbyState>);

  @override
  _i6.Future<void> saveLobbyState(_i3.LobbyState? state) => (super.noSuchMethod(
        Invocation.method(
          #saveLobbyState,
          [state],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> syncLobbyData() => (super.noSuchMethod(
        Invocation.method(
          #syncLobbyData,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> purgeOldData() => (super.noSuchMethod(
        Invocation.method(
          #purgeOldData,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> trackLobbyEvent(
    String? event,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackLobbyEvent,
          [
            event,
            data,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> recordMatchResult({
    required String? lobbyId,
    required String? gameName,
    required String? result,
    required List<String>? playerUids,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordMatchResult,
          [],
          {
            #lobbyId: lobbyId,
            #gameName: gameName,
            #result: result,
            #playerUids: playerUids,
            #notes: notes,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> getLobbyStats(String? lobbyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLobbyStats,
          [lobbyId],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getMatchHistory(String? lobbyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMatchHistory,
          [lobbyId],
        ),
        returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub: _i6.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<void> createInvite(Map<String, dynamic>? inviteData) =>
      (super.noSuchMethod(
        Invocation.method(
          #createInvite,
          [inviteData],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> createPeacock(Map<String, dynamic>? peacockData) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPeacock,
          [peacockData],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateUserPeacock(
    String? userId,
    Map<String, dynamic>? peacockStatus,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserPeacock,
          [
            userId,
            peacockStatus,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Stream<_i2.Lobby?> getLobbyStream(String? lobbyId) => (super.noSuchMethod(
        Invocation.method(
          #getLobbyStream,
          [lobbyId],
        ),
        returnValue: _i6.Stream<_i2.Lobby?>.empty(),
      ) as _i6.Stream<_i2.Lobby?>);

  @override
  _i6.Stream<List<_i2.Lobby>> getUserLobbiesStream(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserLobbiesStream,
          [userId],
        ),
        returnValue: _i6.Stream<List<_i2.Lobby>>.empty(),
      ) as _i6.Stream<List<_i2.Lobby>>);

  @override
  _i6.Stream<List<_i2.Lobby>> getPublicLobbiesStream({
    bool? isActive,
    String? gameFocus,
    int? limit,
    String? orderBy,
    bool? ascending,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPublicLobbiesStream,
          [],
          {
            #isActive: isActive,
            #gameFocus: gameFocus,
            #limit: limit,
            #orderBy: orderBy,
            #ascending: ascending,
          },
        ),
        returnValue: _i6.Stream<List<_i2.Lobby>>.empty(),
      ) as _i6.Stream<List<_i2.Lobby>>);
}

/// A class which mocks [TimerServiceNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimerServiceNotifier extends _i1.Mock
    implements _i7.TimerServiceNotifier {
  MockTimerServiceNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  _i6.Stream<_i4.AsyncValue<void>> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i6.Stream<_i4.AsyncValue<void>>.empty(),
      ) as _i6.Stream<_i4.AsyncValue<void>>);

  @override
  _i4.AsyncValue<void> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAsyncValue_2<void>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.AsyncValue<void>);

  @override
  _i4.AsyncValue<void> get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _FakeAsyncValue_2<void>(
          this,
          Invocation.getter(#debugState),
        ),
      ) as _i4.AsyncValue<void>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  set onError(_i4.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set state(_i4.AsyncValue<void>? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> startSpotTimer(
    String? gameName,
    String? userId,
    Duration? duration,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #startSpotTimer,
          [
            gameName,
            userId,
            duration,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> startPeacockTimer(
    String? userId,
    Duration? duration,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #startPeacockTimer,
          [
            userId,
            duration,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> stopTimer(String? key) => (super.noSuchMethod(
        Invocation.method(
          #stopTimer,
          [key],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  Duration getRemainingTime(
    String? key, {
    bool? interpolate = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRemainingTime,
          [key],
          {#interpolate: interpolate},
        ),
        returnValue: _FakeDuration_3(
          this,
          Invocation.method(
            #getRemainingTime,
            [key],
            {#interpolate: interpolate},
          ),
        ),
      ) as Duration);

  @override
  _i6.Stream<Duration> observeTimer(String? key) => (super.noSuchMethod(
        Invocation.method(
          #observeTimer,
          [key],
        ),
        returnValue: _i6.Stream<Duration>.empty(),
      ) as _i6.Stream<Duration>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i4.AsyncValue<void>? old,
    _i4.AsyncValue<void>? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.RemoveListener addListener(
    _i8.Listener<_i4.AsyncValue<void>>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
      ) as _i4.RemoveListener);
}
