targets:
  $default:
    builders:
      riverpod_generator:
        generate_for:
          - lib/**/*.dart
        options:
          provider_name_suffix: 'Provider'
          provider_implementation_suffix: 'Impl'