name: cod_squad_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_database: ^11.1.4
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.3
  firebase_auth: ^5.5.1
  audioplayers: ^6.1.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.0
  fl_chart: ^0.68.0
  flutter_local_notifications: ^17.2.3
  table_calendar: ^3.1.2
  intl: ^0.19.0
  timezone: ^0.9.2
  image_picker: ^1.1.2
  flutter_animate: ^4.5.0
  url_launcher: ^6.3.0
  video_player: ^2.9.2
  record: ^5.1.2
  cached_network_image: ^3.4.0
  clipboard: ^0.1.3
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  assets:
    - assets/images/read_icon.png
    - assets/images/photo_icon.png
    - assets/images/signout_icon.png  # Note: You have signout_icon.png, but code uses signout.png
    - assets/images/send_icon.png
    - assets/images/warning.png
    - assets/images/military_tech.png
    - assets/images/mic_on_icon.png
    - assets/images/mic_off_icon.png
    - assets/sounds/duck.mp3
    - assets/sounds/turducken.wav
    - assets/sounds/turkey.wav
    - assets/sounds/victory.mp3
    - assets/images/turkey.png
    - assets/images/duck.png
    - assets/images/chicken.png
    - assets/images/logo.png
    - assets/images/splash_background.png
    - assets/images/performance.png
    - assets/images/availability.png
    - assets/images/squad.png
    - assets/images/chat.png
    - assets/images/placeholder.png
    - assets/images/check.png
    - assets/images/close.png
    - assets/images/info_icon.png
    - assets/images/notifications_off_icon.png
    - assets/images/delete_sweep_icon.png
    - assets/images/exit_icon.png
    - assets/images/search_icon.png
    - assets/images/edit_icon.png
    - assets/images/copy_icon.png
    - assets/images/forward_icon.png
    - assets/images/delete_icon.png
    - assets/images/emoji_icon.png
    - assets/images/clock_icon.png
    - assets/images/done_all_icon.png
    - assets/images/play_icon.png
    - assets/images/pause_icon.png
    # Added missing assets
    - assets/images/clear_icon.png
    - assets/images/mute_icon.png
    - assets/images/leave_icon.png
    - assets/images/image_icon.png
    - assets/images/react_icon.png
    - assets/images/signout.png  # Added since code references signout.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21