buildscript {
  repositories {
    google()
    mavenCentral()
  }
  dependencies {
    classpath 'com.android.tools.build:gradle:8.9.1' // Update as needed
    classpath 'com.google.gms:google-services:4.4.2' // Add this
  }
}

allprojects {
  repositories {
    google()
    mavenCentral()
  }
}