org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=1024M -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.14.7-hotspot
org.gradle.daemon=true
org.gradle.offline=false
android.useAndroidX=true
android.enableJetifier=true
# Comments can go on separate lines like this