// Mocks generated by Mockito 5.4.6 from annotations
// in squad_sync/test/services/onboarding_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:cloud_firestore/cloud_firestore.dart' as _i8;
import 'package:firebase_auth/firebase_auth.dart' as _i9;
import 'package:flutter/material.dart' as _i11;
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_preferences/shared_preferences.dart' as _i6;
import 'package:squad_sync/providers/game_notifier.dart' as _i4;
import 'package:squad_sync/providers/system_notifier.dart' as _i5;
import 'package:squad_sync/providers/user_notifier.dart' as _i3;
import 'package:squad_sync/services/igdb_auth_service.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAutoDisposeAsyncNotifierProviderRef_0<T> extends _i1.SmartFake
    implements _i2.AutoDisposeAsyncNotifierProviderRef<T> {
  _FakeAutoDisposeAsyncNotifierProviderRef_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAsyncValue_1<T> extends _i1.SmartFake implements _i2.AsyncValue<T> {
  _FakeAsyncValue_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserState_2 extends _i1.SmartFake implements _i3.UserState {
  _FakeUserState_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGameState_3 extends _i1.SmartFake implements _i4.GameState {
  _FakeGameState_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSystemState_4 extends _i1.SmartFake implements _i5.SystemState {
  _FakeSystemState_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i6.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() => (super.noSuchMethod(
        Invocation.method(
          #getKeys,
          [],
        ),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  Object? get(String? key) => (super.noSuchMethod(Invocation.method(
        #get,
        [key],
      )) as Object?);

  @override
  bool? getBool(String? key) => (super.noSuchMethod(Invocation.method(
        #getBool,
        [key],
      )) as bool?);

  @override
  int? getInt(String? key) => (super.noSuchMethod(Invocation.method(
        #getInt,
        [key],
      )) as int?);

  @override
  double? getDouble(String? key) => (super.noSuchMethod(Invocation.method(
        #getDouble,
        [key],
      )) as double?);

  @override
  String? getString(String? key) => (super.noSuchMethod(Invocation.method(
        #getString,
        [key],
      )) as String?);

  @override
  bool containsKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #getStringList,
        [key],
      )) as List<String>?);

  @override
  _i7.Future<bool> setBool(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [
            key,
            value,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> setInt(
    String? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInt,
          [
            key,
            value,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> setDouble(
    String? key,
    double? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDouble,
          [
            key,
            value,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> setString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> setStringList(
    String? key,
    List<String>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setStringList,
          [
            key,
            value,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> commit() => (super.noSuchMethod(
        Invocation.method(
          #commit,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [UserNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserNotifier extends _i1.Mock implements _i3.UserNotifier {
  MockUserNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AutoDisposeAsyncNotifierProviderRef<_i3.UserState> get ref =>
      (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeAutoDisposeAsyncNotifierProviderRef_0<_i3.UserState>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.AutoDisposeAsyncNotifierProviderRef<_i3.UserState>);

  @override
  _i2.AsyncValue<_i3.UserState> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAsyncValue_1<_i3.UserState>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.AsyncValue<_i3.UserState>);

  @override
  _i7.Future<_i3.UserState> get future => (super.noSuchMethod(
        Invocation.getter(#future),
        returnValue: _i7.Future<_i3.UserState>.value(_FakeUserState_2(
          this,
          Invocation.getter(#future),
        )),
      ) as _i7.Future<_i3.UserState>);

  @override
  set state(_i2.AsyncValue<_i3.UserState>? newState) => super.noSuchMethod(
        Invocation.setter(
          #state,
          newState,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i3.UserState> build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _i7.Future<_i3.UserState>.value(_FakeUserState_2(
          this,
          Invocation.method(
            #build,
            [],
          ),
        )),
      ) as _i7.Future<_i3.UserState>);

  @override
  _i7.Future<void> updateProfileImage(String? url) => (super.noSuchMethod(
        Invocation.method(
          #updateProfileImage,
          [url],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateDisplayName(String? name) => (super.noSuchMethod(
        Invocation.method(
          #updateDisplayName,
          [name],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> blockUser(String? userName) => (super.noSuchMethod(
        Invocation.method(
          #blockUser,
          [userName],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> unblockUser(String? userName) => (super.noSuchMethod(
        Invocation.method(
          #unblockUser,
          [userName],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  bool isBlocked(String? userName) => (super.noSuchMethod(
        Invocation.method(
          #isBlocked,
          [userName],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> addBan(
    String? userName,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addBan,
          [
            userName,
            reason,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  bool isBanned(String? userName) => (super.noSuchMethod(
        Invocation.method(
          #isBanned,
          [userName],
        ),
        returnValue: false,
      ) as bool);

  @override
  int getBanCount(String? userName) => (super.noSuchMethod(
        Invocation.method(
          #getBanCount,
          [userName],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i7.Future<void> addPinnedGame(Map<String, dynamic>? game) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPinnedGame,
          [game],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removePinnedGame(String? gameName) => (super.noSuchMethod(
        Invocation.method(
          #removePinnedGame,
          [gameName],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void updateMemberProfileImage(
    String? uid,
    String? imageUrl,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateMemberProfileImage,
          [
            uid,
            imageUrl,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateUserProfileCache(
    String? uid,
    Map<String, dynamic>? profile,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateUserProfileCache,
          [
            uid,
            profile,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenSelf(
    void Function(
      _i2.AsyncValue<_i3.UserState>?,
      _i2.AsyncValue<_i3.UserState>,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i3.UserState> update(
    _i7.FutureOr<_i3.UserState> Function(_i3.UserState)? cb, {
    _i7.FutureOr<_i3.UserState> Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [cb],
          {#onError: onError},
        ),
        returnValue: _i7.Future<_i3.UserState>.value(_FakeUserState_2(
          this,
          Invocation.method(
            #update,
            [cb],
            {#onError: onError},
          ),
        )),
      ) as _i7.Future<_i3.UserState>);

  @override
  bool updateShouldNotify(
    _i2.AsyncValue<_i3.UserState>? previous,
    _i2.AsyncValue<_i3.UserState>? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [GameNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameNotifier extends _i1.Mock implements _i4.GameNotifier {
  MockGameNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set firestore(_i8.FirebaseFirestore? _firestore) => super.noSuchMethod(
        Invocation.setter(
          #firestore,
          _firestore,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set auth(_i9.FirebaseAuth? _auth) => super.noSuchMethod(
        Invocation.setter(
          #auth,
          _auth,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set igdbAuthService(_i10.IgdbAuthService? _igdbAuthService) =>
      super.noSuchMethod(
        Invocation.setter(
          #igdbAuthService,
          _igdbAuthService,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.AutoDisposeAsyncNotifierProviderRef<_i4.GameState> get ref =>
      (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeAutoDisposeAsyncNotifierProviderRef_0<_i4.GameState>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.AutoDisposeAsyncNotifierProviderRef<_i4.GameState>);

  @override
  _i2.AsyncValue<_i4.GameState> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAsyncValue_1<_i4.GameState>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.AsyncValue<_i4.GameState>);

  @override
  _i7.Future<_i4.GameState> get future => (super.noSuchMethod(
        Invocation.getter(#future),
        returnValue: _i7.Future<_i4.GameState>.value(_FakeGameState_3(
          this,
          Invocation.getter(#future),
        )),
      ) as _i7.Future<_i4.GameState>);

  @override
  set state(_i2.AsyncValue<_i4.GameState>? newState) => super.noSuchMethod(
        Invocation.setter(
          #state,
          newState,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i4.GameState> build({
    _i8.FirebaseFirestore? firestore,
    _i9.FirebaseAuth? auth,
    _i10.IgdbAuthService? igdbAuthService,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
          {
            #firestore: firestore,
            #auth: auth,
            #igdbAuthService: igdbAuthService,
          },
        ),
        returnValue: _i7.Future<_i4.GameState>.value(_FakeGameState_3(
          this,
          Invocation.method(
            #build,
            [],
            {
              #firestore: firestore,
              #auth: auth,
              #igdbAuthService: igdbAuthService,
            },
          ),
        )),
      ) as _i7.Future<_i4.GameState>);

  @override
  _i7.Future<void> selectGame(Map<String, dynamic>? game) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectGame,
          [game],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getPinnedGamesWithContext() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPinnedGamesWithContext,
          [],
        ),
        returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<void> searchGames(String? query) => (super.noSuchMethod(
        Invocation.method(
          #searchGames,
          [query],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> searchGamesIGDB(
    _i11.BuildContext? context,
    String? query,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchGamesIGDB,
          [
            context,
            query,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> retrySearchIGDB(
    _i11.BuildContext? context,
    String? query,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #retrySearchIGDB,
          [
            context,
            query,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> createLobby(
    String? gameName,
    Map<String, dynamic>? settings,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLobby,
          [
            gameName,
            settings,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> joinLobby(String? lobbyId) => (super.noSuchMethod(
        Invocation.method(
          #joinLobby,
          [lobbyId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> leaveLobby(String? lobbyId) => (super.noSuchMethod(
        Invocation.method(
          #leaveLobby,
          [lobbyId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> completeOnboardingStep(
    String? step,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeOnboardingStep,
          [
            step,
            data,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> pinGame(Map<String, dynamic>? game) => (super.noSuchMethod(
        Invocation.method(
          #pinGame,
          [game],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> unpinGame(String? gameName) => (super.noSuchMethod(
        Invocation.method(
          #unpinGame,
          [gameName],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> addToGameHistory(Map<String, dynamic>? gameEntry) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToGameHistory,
          [gameEntry],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> handleSearchError(
    _i11.BuildContext? context,
    String? query,
    dynamic error,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleSearchError,
          [
            context,
            query,
            error,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getOnboardingGames() =>
      (super.noSuchMethod(
        Invocation.method(
          #getOnboardingGames,
          [],
        ),
        returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<void> selectGameWithTracking(Map<String, dynamic>? game) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectGameWithTracking,
          [game],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void listenSelf(
    void Function(
      _i2.AsyncValue<_i4.GameState>?,
      _i2.AsyncValue<_i4.GameState>,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i4.GameState> update(
    _i7.FutureOr<_i4.GameState> Function(_i4.GameState)? cb, {
    _i7.FutureOr<_i4.GameState> Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [cb],
          {#onError: onError},
        ),
        returnValue: _i7.Future<_i4.GameState>.value(_FakeGameState_3(
          this,
          Invocation.method(
            #update,
            [cb],
            {#onError: onError},
          ),
        )),
      ) as _i7.Future<_i4.GameState>);

  @override
  bool updateShouldNotify(
    _i2.AsyncValue<_i4.GameState>? previous,
    _i2.AsyncValue<_i4.GameState>? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [SystemNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockSystemNotifier extends _i1.Mock implements _i5.SystemNotifier {
  MockSystemNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set auth(_i9.FirebaseAuth? _auth) => super.noSuchMethod(
        Invocation.setter(
          #auth,
          _auth,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set firestore(_i8.FirebaseFirestore? _firestore) => super.noSuchMethod(
        Invocation.setter(
          #firestore,
          _firestore,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.AutoDisposeAsyncNotifierProviderRef<_i5.SystemState> get ref =>
      (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue:
            _FakeAutoDisposeAsyncNotifierProviderRef_0<_i5.SystemState>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.AutoDisposeAsyncNotifierProviderRef<_i5.SystemState>);

  @override
  _i2.AsyncValue<_i5.SystemState> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAsyncValue_1<_i5.SystemState>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.AsyncValue<_i5.SystemState>);

  @override
  _i7.Future<_i5.SystemState> get future => (super.noSuchMethod(
        Invocation.getter(#future),
        returnValue: _i7.Future<_i5.SystemState>.value(_FakeSystemState_4(
          this,
          Invocation.getter(#future),
        )),
      ) as _i7.Future<_i5.SystemState>);

  @override
  set state(_i2.AsyncValue<_i5.SystemState>? newState) => super.noSuchMethod(
        Invocation.setter(
          #state,
          newState,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i5.SystemState> build({
    _i9.FirebaseAuth? auth,
    _i8.FirebaseFirestore? firestore,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
          {
            #auth: auth,
            #firestore: firestore,
          },
        ),
        returnValue: _i7.Future<_i5.SystemState>.value(_FakeSystemState_4(
          this,
          Invocation.method(
            #build,
            [],
            {
              #auth: auth,
              #firestore: firestore,
            },
          ),
        )),
      ) as _i7.Future<_i5.SystemState>);

  @override
  _i7.Future<void> addNotification(Map<String, dynamic>? notification) =>
      (super.noSuchMethod(
        Invocation.method(
          #addNotification,
          [notification],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> markNotificationsAsRead() => (super.noSuchMethod(
        Invocation.method(
          #markNotificationsAsRead,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteNotification(String? notificationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteNotification,
          [notificationId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> addAvailabilitySlot(Map<String, dynamic>? slot) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAvailabilitySlot,
          [slot],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeAvailabilitySlot(String? slotId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeAvailabilitySlot,
          [slotId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateAvailabilitySlot(
    String? slotId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAvailabilitySlot,
          [
            slotId,
            updates,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> submitBanVote(
    String? targetUserId,
    bool? vote,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitBanVote,
          [
            targetUserId,
            vote,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> processBanVotes() => (super.noSuchMethod(
        Invocation.method(
          #processBanVotes,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> sendNotificationToUser(
    String? userId,
    String? title,
    String? body, {
    Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendNotificationToUser,
          [
            userId,
            title,
            body,
          ],
          {#data: data},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> sendNotificationToSquad(
    String? squadId,
    String? title,
    String? body, {
    Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendNotificationToSquad,
          [
            squadId,
            title,
            body,
          ],
          {#data: data},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> scheduleNotification(
    DateTime? scheduledTime,
    String? title,
    String? body, {
    Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleNotification,
          [
            scheduledTime,
            title,
            body,
          ],
          {#data: data},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void showSystemAlert(String? message) => super.noSuchMethod(
        Invocation.method(
          #showSystemAlert,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showMaintenanceAlert(String? message) => super.noSuchMethod(
        Invocation.method(
          #showMaintenanceAlert,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> clearOldNotifications({Duration? olderThan}) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearOldNotifications,
          [],
          {#olderThan: olderThan},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> resetDailyVotes() => (super.noSuchMethod(
        Invocation.method(
          #resetDailyVotes,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void listenSelf(
    void Function(
      _i2.AsyncValue<_i5.SystemState>?,
      _i2.AsyncValue<_i5.SystemState>,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i5.SystemState> update(
    _i7.FutureOr<_i5.SystemState> Function(_i5.SystemState)? cb, {
    _i7.FutureOr<_i5.SystemState> Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [cb],
          {#onError: onError},
        ),
        returnValue: _i7.Future<_i5.SystemState>.value(_FakeSystemState_4(
          this,
          Invocation.method(
            #update,
            [cb],
            {#onError: onError},
          ),
        )),
      ) as _i7.Future<_i5.SystemState>);

  @override
  bool updateShouldNotify(
    _i2.AsyncValue<_i5.SystemState>? previous,
    _i2.AsyncValue<_i5.SystemState>? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
      ) as bool);
}
