// Mocks generated by Mockito 5.4.6 from annotations
// in squad_sync/test/presentation/notifiers/chat_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:squad_sync/domain/entities/chat_group.dart' as _i3;
import 'package:squad_sync/domain/entities/message.dart' as _i2;
import 'package:squad_sync/domain/repositories/chat_repository.dart' as _i5;
import 'package:squad_sync/services/auth_service_supabase.dart' as _i8;
import 'package:supabase_flutter/supabase_flutter.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMessage_0 extends _i1.SmartFake implements _i2.Message {
  _FakeMessage_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePoll_1 extends _i1.SmartFake implements _i2.Poll {
  _FakePoll_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChatGroup_2 extends _i1.SmartFake implements _i3.ChatGroup {
  _FakeChatGroup_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthResponse_3 extends _i1.SmartFake implements _i4.AuthResponse {
  _FakeAuthResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserResponse_4 extends _i1.SmartFake implements _i4.UserResponse {
  _FakeUserResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i5.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Message> sendMessage(
    String? chatGroupId,
    String? text,
    _i2.MessageType? messageType,
    _i2.ChatType? chatType, {
    String? mediaUrl,
    String? mediaType,
    String? replyTo,
    _i2.Poll? poll,
    String? voiceNoteUrl,
    int? voiceNoteDuration,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [
            chatGroupId,
            text,
            messageType,
            chatType,
          ],
          {
            #mediaUrl: mediaUrl,
            #mediaType: mediaType,
            #replyTo: replyTo,
            #poll: poll,
            #voiceNoteUrl: voiceNoteUrl,
            #voiceNoteDuration: voiceNoteDuration,
          },
        ),
        returnValue: _i6.Future<_i2.Message>.value(_FakeMessage_0(
          this,
          Invocation.method(
            #sendMessage,
            [
              chatGroupId,
              text,
              messageType,
              chatType,
            ],
            {
              #mediaUrl: mediaUrl,
              #mediaType: mediaType,
              #replyTo: replyTo,
              #poll: poll,
              #voiceNoteUrl: voiceNoteUrl,
              #voiceNoteDuration: voiceNoteDuration,
            },
          ),
        )),
      ) as _i6.Future<_i2.Message>);

  @override
  _i6.Future<List<_i2.Message>> loadMessages(
    String? chatGroupId, {
    int? limit = 50,
    DateTime? before,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadMessages,
          [chatGroupId],
          {
            #limit: limit,
            #before: before,
          },
        ),
        returnValue: _i6.Future<List<_i2.Message>>.value(<_i2.Message>[]),
      ) as _i6.Future<List<_i2.Message>>);

  @override
  _i6.Future<void> deleteMessage(
    String? chatGroupId,
    String? messageId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMessage,
          [
            chatGroupId,
            messageId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i2.Message> editMessage(
    String? chatGroupId,
    String? messageId,
    String? newText,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editMessage,
          [
            chatGroupId,
            messageId,
            newText,
          ],
        ),
        returnValue: _i6.Future<_i2.Message>.value(_FakeMessage_0(
          this,
          Invocation.method(
            #editMessage,
            [
              chatGroupId,
              messageId,
              newText,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Message>);

  @override
  _i6.Stream<List<_i2.Message>> watchMessages(String? chatGroupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchMessages,
          [chatGroupId],
        ),
        returnValue: _i6.Stream<List<_i2.Message>>.empty(),
      ) as _i6.Stream<List<_i2.Message>>);

  @override
  _i6.Stream<Map<String, Set<String>>> watchTypingIndicators(
          String? chatGroupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchTypingIndicators,
          [chatGroupId],
        ),
        returnValue: _i6.Stream<Map<String, Set<String>>>.empty(),
      ) as _i6.Stream<Map<String, Set<String>>>);

  @override
  _i6.Stream<Map<String, int>> watchUnreadCounts() => (super.noSuchMethod(
        Invocation.method(
          #watchUnreadCounts,
          [],
        ),
        returnValue: _i6.Stream<Map<String, int>>.empty(),
      ) as _i6.Stream<Map<String, int>>);

  @override
  _i6.Future<void> addReaction(
    String? chatGroupId,
    String? messageId,
    String? reaction,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addReaction,
          [
            chatGroupId,
            messageId,
            reaction,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> removeReaction(
    String? chatGroupId,
    String? messageId,
    String? reaction,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeReaction,
          [
            chatGroupId,
            messageId,
            reaction,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<Map<String, int>> getMessageReactions(
    String? chatGroupId,
    String? messageId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessageReactions,
          [
            chatGroupId,
            messageId,
          ],
        ),
        returnValue: _i6.Future<Map<String, int>>.value(<String, int>{}),
      ) as _i6.Future<Map<String, int>>);

  @override
  _i6.Future<_i2.Poll> createPoll(
    String? chatGroupId,
    String? question,
    List<String>? options,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPoll,
          [
            chatGroupId,
            question,
            options,
          ],
        ),
        returnValue: _i6.Future<_i2.Poll>.value(_FakePoll_1(
          this,
          Invocation.method(
            #createPoll,
            [
              chatGroupId,
              question,
              options,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Poll>);

  @override
  _i6.Future<void> votePoll(
    String? chatGroupId,
    String? pollId,
    String? option,
    String? voterId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #votePoll,
          [
            chatGroupId,
            pollId,
            option,
            voterId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> closePoll(
    String? chatGroupId,
    String? pollId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #closePoll,
          [
            chatGroupId,
            pollId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<Map<String, _i2.Poll>> getActivePolls(String? chatGroupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActivePolls,
          [chatGroupId],
        ),
        returnValue:
            _i6.Future<Map<String, _i2.Poll>>.value(<String, _i2.Poll>{}),
      ) as _i6.Future<Map<String, _i2.Poll>>);

  @override
  _i6.Future<String> uploadMedia(
    String? filePath,
    String? mediaType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadMedia,
          [
            filePath,
            mediaType,
          ],
        ),
        returnValue: _i6.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #uploadMedia,
            [
              filePath,
              mediaType,
            ],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getMediaHistory(String? chatGroupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMediaHistory,
          [chatGroupId],
        ),
        returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<void> deleteMedia(String? mediaUrl) => (super.noSuchMethod(
        Invocation.method(
          #deleteMedia,
          [mediaUrl],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i3.ChatGroup> createGroup(
    String? name,
    bool? isPublic, {
    String? description,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createGroup,
          [
            name,
            isPublic,
          ],
          {#description: description},
        ),
        returnValue: _i6.Future<_i3.ChatGroup>.value(_FakeChatGroup_2(
          this,
          Invocation.method(
            #createGroup,
            [
              name,
              isPublic,
            ],
            {#description: description},
          ),
        )),
      ) as _i6.Future<_i3.ChatGroup>);

  @override
  _i6.Future<void> joinGroup(String? groupId) => (super.noSuchMethod(
        Invocation.method(
          #joinGroup,
          [groupId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> leaveGroup(String? groupId) => (super.noSuchMethod(
        Invocation.method(
          #leaveGroup,
          [groupId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i3.ChatGroup>> discoverGroups({
    String? query,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverGroups,
          [],
          {
            #query: query,
            #limit: limit,
          },
        ),
        returnValue: _i6.Future<List<_i3.ChatGroup>>.value(<_i3.ChatGroup>[]),
      ) as _i6.Future<List<_i3.ChatGroup>>);

  @override
  _i6.Future<_i3.ChatGroup?> getGroupByInviteCode(String? code) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroupByInviteCode,
          [code],
        ),
        returnValue: _i6.Future<_i3.ChatGroup?>.value(),
      ) as _i6.Future<_i3.ChatGroup?>);

  @override
  _i6.Future<void> updateGroupSettings(
    String? groupId,
    Map<String, dynamic>? settings,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateGroupSettings,
          [
            groupId,
            settings,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateTypingIndicator(
    String? chatGroupId,
    bool? isTyping,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTypingIndicator,
          [
            chatGroupId,
            isTyping,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<Map<String, Set<String>>> getTypingIndicators(
          String? chatGroupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTypingIndicators,
          [chatGroupId],
        ),
        returnValue:
            _i6.Future<Map<String, Set<String>>>.value(<String, Set<String>>{}),
      ) as _i6.Future<Map<String, Set<String>>>);

  @override
  _i6.Future<void> pinMessage(
    String? chatGroupId,
    String? messageId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #pinMessage,
          [
            chatGroupId,
            messageId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> unpinMessage(
    String? chatGroupId,
    String? messageId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unpinMessage,
          [
            chatGroupId,
            messageId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<String>> getPinnedMessages(String? chatGroupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPinnedMessages,
          [chatGroupId],
        ),
        returnValue: _i6.Future<List<String>>.value(<String>[]),
      ) as _i6.Future<List<String>>);

  @override
  _i6.Future<String> getAiResponse(
    String? chatGroupId,
    String? userMessage,
    String? context,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAiResponse,
          [
            chatGroupId,
            userMessage,
            context,
          ],
        ),
        returnValue: _i6.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #getAiResponse,
            [
              chatGroupId,
              userMessage,
              context,
            ],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<List<_i2.Message>> searchMessages(
    String? chatGroupId,
    String? query,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMessages,
          [
            chatGroupId,
            query,
          ],
        ),
        returnValue: _i6.Future<List<_i2.Message>>.value(<_i2.Message>[]),
      ) as _i6.Future<List<_i2.Message>>);

  @override
  _i6.Future<void> syncMessages(
    String? chatGroupId, {
    DateTime? since,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncMessages,
          [chatGroupId],
          {#since: since},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getPendingMessages() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingMessages,
          [],
        ),
        returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<void> markMessagesAsRead(
    String? chatGroupId,
    DateTime? timestamp,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markMessagesAsRead,
          [
            chatGroupId,
            timestamp,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> trackMessageAnalytics(
    String? chatGroupId,
    String? messageId,
    String? event,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackMessageAnalytics,
          [
            chatGroupId,
            messageId,
            event,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> getChatAnalytics(String? chatGroupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChatAnalytics,
          [chatGroupId],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<void> startVoiceChat(String? chatGroupId) => (super.noSuchMethod(
        Invocation.method(
          #startVoiceChat,
          [chatGroupId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> endVoiceChat(String? chatGroupId) => (super.noSuchMethod(
        Invocation.method(
          #endVoiceChat,
          [chatGroupId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> joinVoiceChat(String? chatGroupId) => (super.noSuchMethod(
        Invocation.method(
          #joinVoiceChat,
          [chatGroupId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> leaveVoiceChat(String? chatGroupId) => (super.noSuchMethod(
        Invocation.method(
          #leaveVoiceChat,
          [chatGroupId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<String>> getVoiceChatParticipants(String? chatGroupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVoiceChatParticipants,
          [chatGroupId],
        ),
        returnValue: _i6.Future<List<String>>.value(<String>[]),
      ) as _i6.Future<List<String>>);
}

/// A class which mocks [AuthServiceSupabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthServiceSupabase extends _i1.Mock
    implements _i8.AuthServiceSupabase {
  MockAuthServiceSupabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  _i6.Stream<_i4.AuthState> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i6.Stream<_i4.AuthState>.empty(),
      ) as _i6.Stream<_i4.AuthState>);

  @override
  _i6.Future<_i4.AuthResponse> signInWithEmailPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i6.Future<_i4.AuthResponse>.value(_FakeAuthResponse_3(
          this,
          Invocation.method(
            #signInWithEmailPassword,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i6.Future<_i4.AuthResponse>);

  @override
  _i6.Future<_i4.AuthResponse> signUpWithEmailPassword({
    required String? email,
    required String? password,
    String? displayName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUpWithEmailPassword,
          [],
          {
            #email: email,
            #password: password,
            #displayName: displayName,
          },
        ),
        returnValue: _i6.Future<_i4.AuthResponse>.value(_FakeAuthResponse_3(
          this,
          Invocation.method(
            #signUpWithEmailPassword,
            [],
            {
              #email: email,
              #password: password,
              #displayName: displayName,
            },
          ),
        )),
      ) as _i6.Future<_i4.AuthResponse>);

  @override
  _i6.Future<bool> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> signInWithApple() => (super.noSuchMethod(
        Invocation.method(
          #signInWithApple,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> resetPassword(String? email) => (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [email],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.UserResponse> updateProfile({
    String? displayName,
    String? photoUrl,
    Map<String, dynamic>? additionalData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #displayName: displayName,
            #photoUrl: photoUrl,
            #additionalData: additionalData,
          },
        ),
        returnValue: _i6.Future<_i4.UserResponse>.value(_FakeUserResponse_4(
          this,
          Invocation.method(
            #updateProfile,
            [],
            {
              #displayName: displayName,
              #photoUrl: photoUrl,
              #additionalData: additionalData,
            },
          ),
        )),
      ) as _i6.Future<_i4.UserResponse>);

  @override
  _i6.Future<Map<String, dynamic>?> getJWTClaims() => (super.noSuchMethod(
        Invocation.method(
          #getJWTClaims,
          [],
        ),
        returnValue: _i6.Future<Map<String, dynamic>?>.value(),
      ) as _i6.Future<Map<String, dynamic>?>);

  @override
  _i6.Future<bool> verifyCustomClaim(
    String? metadataType,
    String? claimKey, [
    dynamic expectedValue,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyCustomClaim,
          [
            metadataType,
            claimKey,
            expectedValue,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<String?> getUserRole() => (super.noSuchMethod(
        Invocation.method(
          #getUserRole,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);
}
