// Mocks generated by Mockito 5.4.6 from annotations
// in squad_sync/test/presentation/notifiers/user_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:squad_sync/domain/entities/app_user.dart' as _i5;
import 'package:squad_sync/domain/repositories/user_repository.dart' as _i3;
import 'package:squad_sync/services/auth_service_supabase.dart' as _i6;
import 'package:squad_sync/services/friends_service.dart' as _i7;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResponse_0 extends _i1.SmartFake implements _i2.AuthResponse {
  _FakeAuthResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserResponse_1 extends _i1.SmartFake implements _i2.UserResponse {
  _FakeUserResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i3.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.AppUser?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i4.Future<_i5.AppUser?>.value(),
      ) as _i4.Future<_i5.AppUser?>);

  @override
  _i4.Future<void> updateProfileImage(String? url) => (super.noSuchMethod(
        Invocation.method(
          #updateProfileImage,
          [url],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateDisplayName(String? name) => (super.noSuchMethod(
        Invocation.method(
          #updateDisplayName,
          [name],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> blockUser(String? userName) => (super.noSuchMethod(
        Invocation.method(
          #blockUser,
          [userName],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> unblockUser(String? userName) => (super.noSuchMethod(
        Invocation.method(
          #unblockUser,
          [userName],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isBlocked(String? userName) => (super.noSuchMethod(
        Invocation.method(
          #isBlocked,
          [userName],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> addBan(
    String? userName,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addBan,
          [
            userName,
            reason,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isBanned(String? userName) => (super.noSuchMethod(
        Invocation.method(
          #isBanned,
          [userName],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<int> getBanCount(String? userName) => (super.noSuchMethod(
        Invocation.method(
          #getBanCount,
          [userName],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> addPinnedGame(Map<String, dynamic>? game) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPinnedGame,
          [game],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removePinnedGame(String? gameName) => (super.noSuchMethod(
        Invocation.method(
          #removePinnedGame,
          [gameName],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateMemberProfileImage(
    String? uid,
    String? imageUrl,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMemberProfileImage,
          [
            uid,
            imageUrl,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateUserProfileCache(
    String? uid,
    Map<String, dynamic>? profile,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfileCache,
          [
            uid,
            profile,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, String?>> getMemberProfileImages() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMemberProfileImages,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, String?>>.value(<String, String?>{}),
      ) as _i4.Future<Map<String, String?>>);

  @override
  _i4.Future<Map<String, Map<String, dynamic>>> getUserProfileCache() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProfileCache,
          [],
        ),
        returnValue: _i4.Future<Map<String, Map<String, dynamic>>>.value(
            <String, Map<String, dynamic>>{}),
      ) as _i4.Future<Map<String, Map<String, dynamic>>>);
}

/// A class which mocks [AuthServiceSupabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthServiceSupabase extends _i1.Mock
    implements _i6.AuthServiceSupabase {
  MockAuthServiceSupabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  _i4.Stream<_i2.AuthState> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i4.Stream<_i2.AuthState>.empty(),
      ) as _i4.Stream<_i2.AuthState>);

  @override
  _i4.Future<_i2.AuthResponse> signInWithEmailPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i4.Future<_i2.AuthResponse>.value(_FakeAuthResponse_0(
          this,
          Invocation.method(
            #signInWithEmailPassword,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i4.Future<_i2.AuthResponse>);

  @override
  _i4.Future<_i2.AuthResponse> signUpWithEmailPassword({
    required String? email,
    required String? password,
    String? displayName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUpWithEmailPassword,
          [],
          {
            #email: email,
            #password: password,
            #displayName: displayName,
          },
        ),
        returnValue: _i4.Future<_i2.AuthResponse>.value(_FakeAuthResponse_0(
          this,
          Invocation.method(
            #signUpWithEmailPassword,
            [],
            {
              #email: email,
              #password: password,
              #displayName: displayName,
            },
          ),
        )),
      ) as _i4.Future<_i2.AuthResponse>);

  @override
  _i4.Future<bool> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> signInWithApple() => (super.noSuchMethod(
        Invocation.method(
          #signInWithApple,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> resetPassword(String? email) => (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [email],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.UserResponse> updateProfile({
    String? displayName,
    String? photoUrl,
    Map<String, dynamic>? additionalData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #displayName: displayName,
            #photoUrl: photoUrl,
            #additionalData: additionalData,
          },
        ),
        returnValue: _i4.Future<_i2.UserResponse>.value(_FakeUserResponse_1(
          this,
          Invocation.method(
            #updateProfile,
            [],
            {
              #displayName: displayName,
              #photoUrl: photoUrl,
              #additionalData: additionalData,
            },
          ),
        )),
      ) as _i4.Future<_i2.UserResponse>);

  @override
  _i4.Future<Map<String, dynamic>?> getJWTClaims() => (super.noSuchMethod(
        Invocation.method(
          #getJWTClaims,
          [],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<bool> verifyCustomClaim(
    String? metadataType,
    String? claimKey, [
    dynamic expectedValue,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyCustomClaim,
          [
            metadataType,
            claimKey,
            expectedValue,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<String?> getUserRole() => (super.noSuchMethod(
        Invocation.method(
          #getUserRole,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);
}

/// A class which mocks [FriendsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFriendsService extends _i1.Mock implements _i7.FriendsService {
  MockFriendsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<Map<String, dynamic>>> searchUsers(
    String? query, {
    String? filter = 'all',
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchUsers,
          [query],
          {
            #filter: filter,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>?> getUserByUid(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserByUid,
          [uid],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<bool> sendFriendRequest(
    String? currentUserId,
    String? targetUserId, {
    String? message,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendFriendRequest,
          [
            currentUserId,
            targetUserId,
          ],
          {#message: message},
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Stream<List<Map<String, dynamic>>> streamPendingRequests(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamPendingRequests,
          [userId],
        ),
        returnValue: _i4.Stream<List<Map<String, dynamic>>>.empty(),
      ) as _i4.Stream<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getPendingRequestsWithDetails(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingRequestsWithDetails,
          [userId],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<bool> acceptFriendRequest(String? requestId) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptFriendRequest,
          [requestId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> declineFriendRequest(String? requestId) =>
      (super.noSuchMethod(
        Invocation.method(
          #declineFriendRequest,
          [requestId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> cancelFriendRequest(
    String? currentUserId,
    String? targetUserId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelFriendRequest,
          [
            currentUserId,
            targetUserId,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Stream<List<Map<String, dynamic>>> streamFriends(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamFriends,
          [userId],
        ),
        returnValue: _i4.Stream<List<Map<String, dynamic>>>.empty(),
      ) as _i4.Stream<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getFriendsWithDetails(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFriendsWithDetails,
          [userId],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<bool> removeFriend(
    String? currentUserId,
    String? friendUid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFriend,
          [
            currentUserId,
            friendUid,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> areFriends(
    String? userId1,
    String? userId2,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #areFriends,
          [
            userId1,
            userId2,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<String?> startDMThread(
    String? currentUserId,
    String? friendUid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #startDMThread,
          [
            currentUserId,
            friendUid,
          ],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<bool> sendDirectMessage({
    required String? senderId,
    required String? recipientId,
    required String? text,
    String? messageType = 'text',
    String? mediaUrl,
    String? mediaType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendDirectMessage,
          [],
          {
            #senderId: senderId,
            #recipientId: recipientId,
            #text: text,
            #messageType: messageType,
            #mediaUrl: mediaUrl,
            #mediaType: mediaType,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Stream<List<Map<String, dynamic>>> streamDirectMessages(
    String? userId1,
    String? userId2,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamDirectMessages,
          [
            userId1,
            userId2,
          ],
        ),
        returnValue: _i4.Stream<List<Map<String, dynamic>>>.empty(),
      ) as _i4.Stream<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getDirectMessages(
    String? userId1,
    String? userId2, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDirectMessages,
          [
            userId1,
            userId2,
          ],
          {#limit: limit},
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<bool> markDMAsRead(
    String? messageId,
    String? recipientId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markDMAsRead,
          [
            messageId,
            recipientId,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<int> getUnreadDMCount(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getUnreadDMCount,
          [userId],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<bool> muteGame(
    String? userId,
    String? gameSlug,
    String? gameName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #muteGame,
          [
            userId,
            gameSlug,
            gameName,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> unmuteGame(
    String? userId,
    String? gameSlug,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unmuteGame,
          [
            userId,
            gameSlug,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getMutedGames(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMutedGames,
          [userId],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<bool> clearMutedGames(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #clearMutedGames,
          [userId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> isGameMuted(
    String? userId,
    String? gameSlug,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isGameMuted,
          [
            userId,
            gameSlug,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
