// Mocks generated by Mockito 5.4.6 from annotations
// in squad_sync/test/screens/discovery_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i10;

import 'package:cloud_firestore/cloud_firestore.dart' as _i9;
import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:sqflite/sqflite.dart' as _i3;
import 'package:squad_sync/chat/sqlite_helper.dart' as _i11;
import 'package:squad_sync/managers/notification_manager.dart' as _i7;
import 'package:squad_sync/services/firestore_service.dart' as _i2;
import 'package:squad_sync/services/grok_service.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeQueryBuilder_0 extends _i1.SmartFake implements _i2.QueryBuilder {
  _FakeQueryBuilder_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabase_1 extends _i1.SmartFake implements _i3.Database {
  _FakeDatabase_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i2.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.QueryBuilder get queryBuilder => (super.noSuchMethod(
        Invocation.getter(#queryBuilder),
        returnValue: _FakeQueryBuilder_0(
          this,
          Invocation.getter(#queryBuilder),
        ),
      ) as _i2.QueryBuilder);

  @override
  void registerField<T>(_i2.FirestoreFieldSerializer<T>? serializer) =>
      super.noSuchMethod(
        Invocation.method(
          #registerField,
          [serializer],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void markFieldChanged(String? fieldName) => super.noSuchMethod(
        Invocation.method(
          #markFieldChanged,
          [fieldName],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> updateFirestore({
    required Map<String, String>? displayNameCache,
    bool? force = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFirestore,
          [],
          {
            #displayNameCache: displayNameCache,
            #force: force,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveGameSearch(
    String? query,
    Map<String, dynamic>? gameData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveGameSearch,
          [
            query,
            gameData,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> loadFirestoreData(
          {required Map<String, String>? displayNameCache}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadFirestoreData,
          [],
          {#displayNameCache: displayNameCache},
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>?> loadFirestore(
    String? collection,
    String? document,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadFirestore,
          [
            collection,
            document,
          ],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Stream<Map<String, dynamic>?> getVoiceRoomStream(String? roomId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVoiceRoomStream,
          [roomId],
        ),
        returnValue: _i4.Stream<Map<String, dynamic>?>.empty(),
      ) as _i4.Stream<Map<String, dynamic>?>);

  @override
  _i4.Future<void> updateVoiceRoom(
    String? roomId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateVoiceRoom,
          [
            roomId,
            data,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateVoiceParticipant(
    String? roomId,
    String? uid,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateVoiceParticipant,
          [
            roomId,
            uid,
            data,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [GrokService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGrokService extends _i1.Mock implements _i5.GrokService {
  MockGrokService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool isMessageForGrok(String? message) => (super.noSuchMethod(
        Invocation.method(
          #isMessageForGrok,
          [message],
        ),
        returnValue: false,
      ) as bool);

  @override
  String cleanGrokMessage(String? message) => (super.noSuchMethod(
        Invocation.method(
          #cleanGrokMessage,
          [message],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #cleanGrokMessage,
            [message],
          ),
        ),
      ) as String);

  @override
  _i4.Future<String> getGrokResponse(
    String? userMessage, {
    String? context,
    List<String>? recentMessages,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGrokResponse,
          [userMessage],
          {
            #context: context,
            #recentMessages: recentMessages,
          },
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #getGrokResponse,
            [userMessage],
            {
              #context: context,
              #recentMessages: recentMessages,
            },
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> suggestSquadsForPinnedGames(
          List<Map<String, dynamic>>? pinnedGames) =>
      (super.noSuchMethod(
        Invocation.method(
          #suggestSquadsForPinnedGames,
          [pinnedGames],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #suggestSquadsForPinnedGames,
            [pinnedGames],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<List<double>> getGroupEmbeddings(
          Map<String, dynamic>? groupData) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroupEmbeddings,
          [groupData],
        ),
        returnValue: _i4.Future<List<double>>.value(<double>[]),
      ) as _i4.Future<List<double>>);

  @override
  _i4.Future<Map<String, double>> scoreRelevance(
    String? searchTerm,
    List<String>? candidates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #scoreRelevance,
          [
            searchTerm,
            candidates,
          ],
        ),
        returnValue: _i4.Future<Map<String, double>>.value(<String, double>{}),
      ) as _i4.Future<Map<String, double>>);
}

/// A class which mocks [NotificationManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationManager extends _i1.Mock
    implements _i7.NotificationManager {
  MockNotificationManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get notificationsEnabled => (super.noSuchMethod(
        Invocation.getter(#notificationsEnabled),
        returnValue: false,
      ) as bool);

  @override
  Map<String, bool> get notificationTypes => (super.noSuchMethod(
        Invocation.getter(#notificationTypes),
        returnValue: <String, bool>{},
      ) as Map<String, bool>);

  @override
  set notificationsEnabled(bool? _notificationsEnabled) => super.noSuchMethod(
        Invocation.setter(
          #notificationsEnabled,
          _notificationsEnabled,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set notificationTypes(Map<String, bool>? _notificationTypes) =>
      super.noSuchMethod(
        Invocation.setter(
          #notificationTypes,
          _notificationTypes,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> updateFCMToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #updateFCMToken,
          [token],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeFCMToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #removeFCMToken,
          [token],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateNotificationSettings(Map<String, bool>? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNotificationSettings,
          [settings],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, bool>> getNotificationSettings() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotificationSettings,
          [],
        ),
        returnValue: _i4.Future<Map<String, bool>>.value(<String, bool>{}),
      ) as _i4.Future<Map<String, bool>>);

  @override
  void setNotificationsEnabled(bool? enabled) => super.noSuchMethod(
        Invocation.method(
          #setNotificationsEnabled,
          [enabled],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setNotificationType(
    String? type,
    bool? enabled,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setNotificationType,
          [
            type,
            enabled,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isNotificationEnabled(String? type) => (super.noSuchMethod(
        Invocation.method(
          #isNotificationEnabled,
          [type],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> showNotification({
    required String? title,
    required String? body,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showNotification,
          [],
          {
            #title: title,
            #body: body,
            #payload: payload,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> scheduleNotification({
    required String? title,
    required String? body,
    required DateTime? scheduledTime,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleNotification,
          [],
          {
            #title: title,
            #body: body,
            #scheduledTime: scheduledTime,
            #payload: payload,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cancelNotification(int? id) => (super.noSuchMethod(
        Invocation.method(
          #cancelNotification,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cancelAllNotifications() => (super.noSuchMethod(
        Invocation.method(
          #cancelAllNotifications,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> showSmartNotification({
    required String? title,
    required String? body,
    required String? channelId,
    String? payload,
    List<_i8.AndroidNotificationAction>? actions,
    bool? ongoing = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showSmartNotification,
          [],
          {
            #title: title,
            #body: body,
            #channelId: channelId,
            #payload: payload,
            #actions: actions,
            #ongoing: ongoing,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> showTimerWarning(
    String? player,
    int? minutesLeft,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #showTimerWarning,
          [
            player,
            minutesLeft,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> showBanWarning(
    String? player,
    int? banCount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #showBanWarning,
          [
            player,
            banCount,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> showAchievementNotification(
    String? player,
    String? achievement,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #showAchievementNotification,
          [
            player,
            achievement,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> showSquadSpotNotification(
    String? game,
    String? spotClaimedBy,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #showSquadSpotNotification,
          [
            game,
            spotClaimedBy,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> showChatMentionNotification(
    String? sender,
    String? message,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #showChatMentionNotification,
          [
            sender,
            message,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> showPersistentLobbyNotification({
    required String? lobbyId,
    required String? gameName,
    required String? hostName,
    required int? currentPlayers,
    required int? maxPlayers,
    required List<String>? playerNames,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showPersistentLobbyNotification,
          [],
          {
            #lobbyId: lobbyId,
            #gameName: gameName,
            #hostName: hostName,
            #currentPlayers: currentPlayers,
            #maxPlayers: maxPlayers,
            #playerNames: playerNames,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> dismissPersistentLobbyNotification(String? lobbyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #dismissPersistentLobbyNotification,
          [lobbyId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> checkAndShowFriendLobbyNotifications() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkAndShowFriendLobbyNotifications,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<List<_i9.QueryDocumentSnapshot<Map<String, dynamic>>>>
      getFilteredNotificationsStream({Set<String>? mutedGames}) =>
          (super.noSuchMethod(
            Invocation.method(
              #getFilteredNotificationsStream,
              [],
              {#mutedGames: mutedGames},
            ),
            returnValue: _i4.Stream<
                List<_i9.QueryDocumentSnapshot<Map<String, dynamic>>>>.empty(),
          ) as _i4
              .Stream<List<_i9.QueryDocumentSnapshot<Map<String, dynamic>>>>);

  @override
  _i4.Stream<int> getUnreadNotificationCount() => (super.noSuchMethod(
        Invocation.method(
          #getUnreadNotificationCount,
          [],
        ),
        returnValue: _i4.Stream<int>.empty(),
      ) as _i4.Stream<int>);

  @override
  _i4.Future<void> createNotification({
    required String? type,
    required String? title,
    required String? body,
    String? game,
    Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNotification,
          [],
          {
            #type: type,
            #title: title,
            #body: body,
            #game: game,
            #data: data,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> markAsRead(String? notificationId) => (super.noSuchMethod(
        Invocation.method(
          #markAsRead,
          [notificationId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> archiveNotification(String? notificationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #archiveNotification,
          [notificationId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SQLiteHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockSQLiteHelper extends _i1.Mock implements _i11.SQLiteHelper {
  MockSQLiteHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i3.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i4.Future<_i3.Database>.value(_FakeDatabase_1(
          this,
          Invocation.getter(#database),
        )),
      ) as _i4.Future<_i3.Database>);

  @override
  _i4.Future<void> insertMessage(
    Map<String, dynamic>? message, {
    String? chatGroupId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertMessage,
          [message],
          {#chatGroupId: chatGroupId},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateMessage(
    String? msgId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMessage,
          [
            msgId,
            updates,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearMessages({String? chatGroupId}) => (super.noSuchMethod(
        Invocation.method(
          #clearMessages,
          [],
          {#chatGroupId: chatGroupId},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getMessages(
    int? offset,
    int? limit, {
    String? chatGroupId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessages,
          [
            offset,
            limit,
          ],
          {#chatGroupId: chatGroupId},
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getCachedGroups(
    String? gameName,
    String? searchTerm,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedGroups,
          [
            gameName,
            searchTerm,
          ],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> cacheGroups(
    List<Map<String, dynamic>>? groups,
    String? gameName,
    String? searchTerm,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheGroups,
          [
            groups,
            gameName,
            searchTerm,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getCachedGames(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedGames,
          [query],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> cacheGames(
    List<Map<String, dynamic>>? games,
    String? query,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheGames,
          [
            games,
            query,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> getCacheMetadata(String? cacheKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCacheMetadata,
          [cacheKey],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> insertCacheMetadata(
    String? cacheKey,
    int? timestamp,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertCacheMetadata,
          [
            cacheKey,
            timestamp,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cleanupExpiredCache(Duration? ttl) => (super.noSuchMethod(
        Invocation.method(
          #cleanupExpiredCache,
          [ttl],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cacheVoiceRoom(
    String? roomId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheVoiceRoom,
          [
            roomId,
            data,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> getCachedVoiceRoom(String? roomId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedVoiceRoom,
          [roomId],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);
}
