-- Add isAiResponse column to chat_messages table
-- This column is used to flag messages that are AI-generated responses from Grok
-- allowing the UI to render them with a distinct bubble style

ALTER TABLE chat_messages
ADD COLUMN IF NOT EXISTS "isAiResponse" BOOLEAN DEFAULT FALSE NOT NULL;

-- Add index for efficient filtering of AI responses
CREATE INDEX IF NOT EXISTS idx_chat_messages_is_ai_response 
ON chat_messages("isAiResponse") 
WHERE "isAiResponse" = TRUE;

-- Add comment for documentation
COMMENT ON COLUMN chat_messages."isAiResponse" IS 
'Flags messages generated by Grok AI. Used by UI to render with distinct bubble style.';
